### ISSUE TITLE
clicking on tool zooms to location a few 100 meter east of actual location

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1112]
### Version
5.1.5

### Browser info
chrome 67

### URL
flamingo4.b3p.nl mobiel

### Where and/or What
location tool

### What happened
clicking on tool zooms to location a few 100 meter east of actual location

### What did you expect?
zoom to correct location

### Reproduce
  1.  click on location tool
  2.  marker is set east of actual location
  3. 
  4.

**Comment by geertplaisier** [comment]
Screen is not zoomed but resized because the right panel is expanded. Discuss what to do and how to fix (center map on markers if present on resizing?)

**Comment by geertplaisier** [comment]
Unable to reproduce this issue. Clicking Current Location adds the marker to the correct location, both on desktop and phone

**Comment by geertplaisier** [comment]
Closing issue, not reproducible
