### ISSUE TITLE
collapsable panel can not be made visible

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1113]
### Version
5.1.5

### Browser info
chrome 67

### URL
flamingo4.b3p.nl mobiel

### Where and/or What
in viewer with closed collapsable panel

### What happened
collapsable panel can not made visible

### What did you expect?
opening panel should be possible

### Reproduce
  1.  configure left menu as floating
  2.  configure right top menu as collapsable, default collapsed
  3.  go to viewer
  4.  try to open right panel by clicking triangle

**Comment by mprins** [comment]
closed with #1162
