### ISSUE TITLE
Message after completing edit ends with text 'undefined' 

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1114]
### Version
5.1.5

### Browser info
chrome 67

### URL
flamingo4.b3p.nl mobiel

### Where and/or What
after saving edit window

### What happened
windows says all went well, but text ends with 'undefined'

### Screenshots
![image](https://user-images.githubusercontent.com/4649741/41994235-1c0b2bfa-7a4e-11e8-8b65-698bcd499d66.png)

### What did you expect?
undefined should not be there.

### Reproduce

  1. edit feature
  2. press save
  3. 
  4.

**Comment by mprins** [comment]
ook gezien op http://geo02.lan.vrln.nl/viewer/app/locatiebeheer
