### ISSUE TITLE
Refresh of (extended) feature info needed after edit

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1115]
### Version
5.1.5

### Browser info
chrome 67

### URL
flamingo4.b3p.nl mobiel

### Where and/or What
extended info with edit link

### What happened
after edit the info visible in the extended info panel is not refreshed

### What did you expect?
after edit the (extended) feature info panel should be refreshed

### Reproduce
  1. have info in extended feature panel
  2. press edit
  3. edit one of the values and save
  4. info in extended feature info panel remains the same.

**Comment by mprins** [comment]
see #1121
