### ISSUE TITLE
Attachment could not be uploaded

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1116]
### Version
5.1.5

### Browser info
chrome 67

### URL
flamingo4.b3p.nl mobiel

### Where and/or What
upload attachment at edit

### What happened
upload started but stopped with error

### Screenshots
![image](https://user-images.githubusercontent.com/4649741/41996192-71b64034-7a54-11e8-8b10-8fa5e8a2c90c.png)

### What did you expect?
succesfull upload

**Comment by mprins** [comment]
probably related:
- #1103
- #1105 
- #1104 (fixed)

**Comment by mprins** [comment]
I think this is fixed with  #1133 and #1105 (v5.3.1)
