### ISSUE TITLE
after edit you can no longer select an object on touch device

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1117]
### Version
5.1.5

### Browser info
chrome 67

### URL
flamingo4.b3p.nl mobiel

### Where and/or What
after edit you can no longer select an object on touch device

### What happened
after edit you can no longer select an object on touch device

### What did you expect?
after edit select new object must be possible on touch

### Reproduce
  1. select object on touch device
  2. edit object
  3. select another object on touch, this is not possible

Possibly the fix for touch devices is deactivated after an edit

**Comment by geertplaisier** [comment]
Closing issue, not reproducible (anymore)
