### ISSUE TITLE
Snapping does not work with edit-tool anymore

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1187]
### Version
Which version of flamingo do you use: 

Version: | 5.3.5
-- | --
Build time: | 24.08.2018 @ 13:58:53 CEST
Build by: | Meine Toonen
Git details
Git branch: | 922ab207344b2ef37d9e6143304d80f040138f96
Git remote url | git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id: | 922ab20
Git commit full id: | 922ab207344b2ef37d9e6143304d80f040138f96
Git commit time: | 24.08.2018 @ 13:55:30 CEST

### Browser info
latest chrome

### URL
https://flamingo4.b3p.nl/viewer/app/Solparc-Groenbeheer/v1

### Where and/or What
(extended) edit tool and snapping

### What happened
geometry edit does not snap anymore (drawing still works with snapping)

### What did you expect?
edit snaps to configured snapping layer

this has wordked in the past, edit-tool has been thoroughly reworked, code to snap seems te be OK, not clear where this went wrog.

### Reproduce
How can we reproduce this? 

configure snapping, e.g. woonplaats
configure edit e.g. BGT
click on object
drag vertix near woonplaats border
no snapping occurs

**Comment by mprins** [comment]
It seems editing is always "on" and cannot be turned off, so featureinfo doesn't work and the last selected feature now stays selected (and in edit mode)

**Comment by mprins** [comment]
this probably happens because the constructor now creates an edit layer before the application has fully initialized
