### ISSUE TITLE
Choose a CRS when building the application and store this in the DB

### ISSUE THREAD

**Issue by mvdstruijk** [flamingo-geocms/flamingo#1238]
Make it possible to choose a CRS when building the application. Show only the CRS options that are available based on the loaded layers.

**Comment by mtoonen** [comment]
see branch: https://github.com/flamingo-geocms/flamingo/tree/feat/multipleProjectionsSupport
b3af1c6fbf210a0121b2e857361992744e3cf93a: Save projection to db. Filtering of CRS options maybe later
