### ISSUE TITLE
Language always english

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#1262]
Setting the language in the viewer-admin to dutch, always results in an english.
https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/java/nl/b3p/viewer/stripes/I18nActionBean.java#L29
This always returns the english version, eventhough L28 is nl_NL locale.

Maybe because the locale on my machine is en-US, it defaults to the en_US resourcebundle?

**Comment by matthijsln** [comment]
Correct, that's the way the getBundle() works: when the specific nl_NL property file cannot be found, the default locale property file is tried first so when system is set to en_US that bundle is returned.

See: https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html#getBundle-java.lang.String-java.util.Locale-java.lang.ClassLoader-

See commit for fix.
