### ISSUE TITLE
Character encoding of internationlization propertiesfile wrong

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#1263]
Now is ACII, should be UTF-8.
All kinds of mergeconflict arise when saving.

**Comment by matthijsln** [comment]
Can't just be changed, read this:

https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle

**Comment by mtoonen** [comment]
But seeing the stackoverflow thread, we could write our own Control, and pass it 
https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/java/nl/b3p/viewer/util/ResourceBundleProvider.java#L25
as an argument. 
Or am I missing something?

Currently, this breaks the workflow: editing the propertiesfile in netbeans, converts diacritical characters to \uXXXX.
