### ISSUE TITLE
"bestand openen"- button present twice in redlining

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1317]
### Version
5.3.10

### Browser info
latest chrome

### URL
https://flamingo5.b3p.nl/viewer/app/Solparc-BAG/v1

### Where and/or What
redlining component

### What happened
"bestand openen"- button present twice

**Comment by mvdstruijk** [comment]
Double translation. Fixed in pullrequest: Bugs/issue#1317

**Comment by mprins** [comment]
#1333
