### ISSUE TITLE
Help does not show, but error message

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1325]
### Version
5.3.10

### Browser info
latest chrome

### URL
https://flamingo5.b3p.nl/viewer/app/Tailormap-Trees/v1

### Where and/or What
help configured in extended feature info

### What happened
Help text could not be found

### Screenshots
![image](https://user-images.githubusercontent.com/4649741/51030224-06d03a00-1599-11e9-830b-30e61a06ce48.png)

### What did you expect?
help text in popup

### Reproduce
How can we reproduce this?

  1. configure help text in component
  2. click on question mark in component
  3. see popup with error
  4.

**Comment by mvdstruijk** [comment]
Configuration fault. 
The help url builds an iframe so it expects a correct URL.
