### ISSUE TITLE
Flamingo Geoserver integration

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1331]
It would be nice when the current loggedin user or usergroup could be passed over to Geoserver. Geoserver in turn can use this information to refine the request.
An extra input field on the serverform in the register with a label "header" will serve this purpose. The administrator may add a header such as "shared-secret-token: [user]/[group]/?". The shared-secret-token may be chosen randomly and serves as authentication (SSL required). The value of the header will at request time be substituted by user name, group name or some other info (to be determined).

The associated Geoserver will use the shared-secret-token header to check for validity and set the value into a role, user or group (Header authentication).

This user, group or role may next be used to refine the request. With Geofence it is possible to add a CQL filter based on this info. Each user gets only it's own data.

**Comment by mtoonen** [comment]
@mvdstruijk  implemented this I think
