### ISSUE TITLE
Featurerequest: "circle"-polygon drawing in edit tool

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#1453]
It would be good to be able to draw (polygon) circles (for new features) in the edit tool.

I'm thinking about an extra combo that appears next to the "New" button when a polygon layer is selected to be able to choose between regular polygon and circular polygon.
For points and lines this option should not be available.

We need this in OIGS

**Comment by geertplaisier** [comment]
See https://github.com/flamingo-geocms/flamingo/pull/1459
