### ISSUE TITLE
Een paar bugs in upload functie en feature requests

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#1559]
### Version
Which version of flamingo do you use: 5.5.5

### Browser info
Chrome versie 77.0.3865.90 (Officiële build) (64-bits)

### URL
http://flamingo5.b3p.nl/viewer/app/VRU_demo

### Where and/or What

1. Bij uploaden krijg je melding dat het niet gelukt is, in logs staat een npe in regel 141 van FileUploadBean. 
2. Bij elke upload komt er een upload vak bij (ik weet niet of je dit echt wil), maar er komt ook een blokje bij in de ballon met featureinfo. 
3. Je kunt de downloads daarmee ook niet zien graag controleren of dit goed werkt).
4. Bij admin verdwijnt het vak om de upload te bewerken zodra je op een ander vak geklikt hebt in het edit tabblad. 
5. Je kunt upload vakjes niet meer verwijderen.

**Comment by mtoonen** [comment]
1. Kan niet reproduceren, kan je de hele log toevoegen?
2. Bedoel je met "elke upload" elke categorie? Dat is de bedoeling.
3. Controle kan via featureinfo en bij het opnieuw bewerken van feature
4. Klopt, ga ik aanpassen. Workaround is de laag opnieuw openen
5. Kan door middel van het tekstveld van de te verwijderen categorie leeg te maken
