### ISSUE TITLE
installation flamingo

### ISSUE THREAD

**Issue by deRightDirection** [flamingo-geocms/flamingo#1569]
latest version of Flamingo

we created an empty schema in Oracle
we configured the data resource in Tomcat for jdbc/geo-viewer
we put down the war-files in tomcat

the war-files got deployed into two applications

the flamingo admin-application tries to create the database but fails with ORA-955, duplicate object, the schema was empty

the war files create a oracle-schema-export.sql-file, where can i find this one?

**Comment by mtoonen** [comment]
Please provide more detailed information:
log file, version number of: flamingo, tomcat, oracle. The viewer (not admin) will run the database scripts. Make sure the configured user has the correct rights (login, create table, etc.).

**Comment by deRightDirection** [comment]
17-Oct-2019 14:55:34.911 SEVERE [http-nio-80-exec-73] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [nl.b3p.viewer.admin.monitoring.GeoServiceMonitoringListener]
	java.lang.NoClassDefFoundError: javax/mail/Address
		at nl.b3p.viewer.admin.monitoring.GeoServiceMonitoringListener.contextInitialized(GeoServiceMonitoringListener.java:55)

how to resolve this error?

result is that when i open the vieweradmin page the following error is shown:
http 404
Message /vieweradmin/

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

TomCat 9.0.26
latest release of Flamingo (5.5.4)
Oracle 12

**Comment by mtoonen** [comment]
add the dependencies from https://repo.b3p.nl/nexus/#browse/browse:public:org%2Fflamingo-mc%2Ftomcat-lib%2F5.5.7%2Ftomcat-lib-5.5.7-tomcat.zip to the tomcat/lib. 

Latest release is 5.5.7, but adding the dependencies should fix this. If not, please provide the whole log file (from both viewer and viewer-admin), not just a snippet.

**Comment by mprins** [comment]
@deRightDirection Your report is missing key information for debugging and/or analysis. Please use one of the provided templates when logging an issue.
