### ISSUE TITLE
viewer is not opening

### ISSUE THREAD

**Issue by deRightDirection** [flamingo-geocms/flamingo#1590]
### Version
5.5.4

### Browser info
latest version firefox

### URL
website is not available on the internet

### Where and/or What
viewer

### What happened
open a viewer and it get stuck on the loading image
in de web console you can see that there are multiple issues...

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/3999790/67950641-46304b80-fbea-11e9-8f6b-ec3e28f4a3e9.png)

### Server log
can i really found something in the server log about issues in the client?

### What did you expect?
the viewer to be opened

### Reproduce
How can we reproduce this? 

I dont know how to reproduce it at your environment

**Comment by mprins** [comment]
> can i really found something in the server log about issues in the client?

sometimes yes, error message are posted back to the server through the FlamingoErrorLogger

it seems odd that you are loading "FlamingoMap-min.js" this is a Flash component AFAIK, I no longer expect that to work.
You need to use an openlayers map

see also eg. https://source.b3partners.nl/Flamingo4/Documentation/Handleiding%20Flamingo4%20applicatiebeheer.pdf and other dcoumentation listed at https://github.com/flamingo-geocms/flamingo/wiki/Documentation#user-guides

**Comment by deRightDirection** [comment]
could you give me a hint how to switch to an openlayers map because i read the manual Applicatiebeheer and now word about a flash component or openlayers component.

I will check out next week the logging as well

**Comment by deRightDirection** [comment]
thanks for the help so far, I managed to start the application now, only some issues with the CRS of the map but that is something else.
