### ISSUE TITLE
WMTS: proxying gives errror "id to load is required for loading"

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#1692]
### Version
5.3.14

### URL
websg02

### Where and/or What
viewer

### What happened
1. Add WMTS service `http://mapproxy.b3p.nl/service?REQUEST=GetCapabilities&SERVICE=WMTS`
2. Check "Use proxy to get maps." checkbox
3. Add any layer to application

Example request:
```
https://websg02.safetymaps.nl/viewer/action/proxy/wms?url=http%3A%2F%2Fmapproxy.b3p.nl%2Fservice%3F&SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=opentopoachtergrondkaart&STYLE=default&TILEMATRIXSET=ngr14&TILEMATRIX=05&TILEROW=17&TILECOL=15&FORMAT=image%2Fpng
```
Results in HTTP 500 exception (see log)

### Server log
<details><summary>relevant section of the server log:</summary>

```
java.lang.IllegalArgumentException: id to load is required for loading
	org.hibernate.event.LoadEvent.<init>(LoadEvent.java:89)
	org.hibernate.event.LoadEvent.<init>(LoadEvent.java:61)
	org.hibernate.impl.SessionImpl.get(SessionImpl.java:1002)
	org.hibernate.impl.SessionImpl.get(SessionImpl.java:998)
	org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:781)
	org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:756)
	nl.b3p.viewer.stripes.ProxyActionBean.getRequestRL(ProxyActionBean.java:238)
	nl.b3p.viewer.stripes.ProxyActionBean.proxyWMS(ProxyActionBean.java:141)
	nl.b3p.viewer.stripes.ProxyActionBean.proxy(ProxyActionBean.java:125)```
```
</details>

**Comment by matthijsln** [comment]
Additionally I tried to proxy a HTTP Basic secured WMTS but that gave a 401 error.

**Comment by mprins** [comment]
- only WMS proxy is implemented
- proxy requests must include the `serviceId`, your request doesn't, probably the code for add that is missing on the client side. Unfortunately the null check isn't done until later in the code (even in the master branch)

**Comment by mtoonen** [comment]
Yes, this is due to using wmts in the proxy. Closing

**Comment by matthijsln** [comment]
Then the proxy checkbox should be disabled.
