### ISSUE TITLE
Status forbidden when requesting service over proxy without credentials

### ISSUE THREAD

**Issue by KevinvdBosch** [flamingo-geocms/flamingo#1842]
### Version
Which version of flamingo do you use: 5.6.1

### Browser info
Firefox / Chrome

### Where and/or What
Viewer component with layers that use the proxy without credentials

### What happened
Layer won't show. 
Status 403 - Forbidden in network requests

### What did you expect?
To see the image of the layers in the viewer

### Reproduce
How can we reproduce this?

  1. Configure a service in the admin
  2. Allow the option to use the proxy to fetch the maps
![afbeelding](https://user-images.githubusercontent.com/27193836/84250349-3c6daf80-ab0c-11ea-928b-b8376bbc5e52.png)
  3. Don't fill out credentials, we only want to use this proxy for services that are secured by IP (external service is secured by IP, not by password)
  4. Open the viewer and turn the new configured layer on. You'll get a blank image. In the network requests from the browser you can see the HTTP status 403.

### Possible solution
Each configured service in the admin gets an ID in the database. When comparing the requests between a service that has credentials ans uses the proxy, and one that doesn't have credentials and uses the proxy, you can see that the ``serviceId`` parameter is missing.  When entering the layerId manually by copying the request URL in another tab and adjusting the URL, the layer will be shown by the proxy:

![afbeelding](https://user-images.githubusercontent.com/27193836/84252195-8fe0fd00-ab0e-11ea-8337-3eb5cd6136be.png)

![afbeelding](https://user-images.githubusercontent.com/27193836/84252518-f5cd8480-ab0e-11ea-8012-e18f20b4c634.png)

**Comment by mprins** [comment]
This is by design; the proxy is not meant to circumvent authorization on possibly secured services, authentication is required.

You can setup a user for the application using the proxied layer with IP wildcard so for the end user access is anonymous
