### ISSUE TITLE
Featureinfo configuration doesn't show all layers (scrollbar doesn't scroll far enough)

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#210]

**Comment by Tom-Kooy** [comment]
It's been tested and it works!

http://maps.vlaardingen.nl/viewer-admin/

Flamingo viewer

Version:	4.8.0-rc4
Build time:	17.02.2017 @ 16:16:03 CET
Build by:	Meine Toonen
Git details
Git branch:	d6d54239a87524235965b75c36f72b9d565d725f
Git remote url	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id:	d6d5423
Git commit full id:	d6d54239a87524235965b75c36f72b9d565d725f
Git commit time:	17.02.2017 @ 16:12:43 CET
