### ISSUE TITLE
Save sprite in database

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#232]
Save sprite for application in database (base64 in application details) and provide up and download controls.

Reduces system administration now needed to change the sprite (placing a sprite at the correct location and entering the URL in the application settings).

For upgrading old versions we could support both options (URL and uploaded sprite), or download the sprite from the URL and save it in the database during upgrading just like the database updater.

**Comment by mprins** [comment]
closing as @geertplaisier  has been doing some promising stuff using svg instead
