### ISSUE TITLE
Allow adding WMS service with internal and external URL

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#265]
Sometimes the server where Flamingo is installed does not have Internet access or a locally installed GeoServer is reachable via localhost and an external URL but the external URL is not accessible from the server itself.

Perhaps an extra configuration option when adding a WMS service is "external URL" just like "Gebruik altijd ingevulde URL in plaats van URLs in GetCapabilities" which ignores the URL in the Capabilities.

**Comment by geertplaisier** [comment]
Proxy + Ingevulde URL gebruiken lost dit op
