### ISSUE TITLE
Featureinfo/maptip: also search for attribute name when alias not found for popup

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#277]
If you configure an application layer for featureinfo/maptip with the name of an attribute in square brackets and then change the alias for the attribute the feature info popup does not show the value of the attribute unless you also update the alias in square brackets in the application layer config. It would be useful if the alias and attribute name both just work.

**Comment by Tom-Kooy** [comment]
I followed the steps from above. Still doesn't work. 

The current version witch is tested:

Version:	5.0.0-beta4
Build time:	03.03.2017 @ 17:06:03 CET
Build by:	Mark Prins
Git details
Git branch:	871c5cc5f0eb321d2569649905e01a8e4789bd29
Git remote url	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id:	871c5cc
Git commit full id:	871c5cc5f0eb321d2569649905e01a8e4789bd29
Git commit time:	03.03.2017 @ 17:03:42 CET
