### ISSUE TITLE
Proxy secured WMS / WFS services

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#279]
A HTTP Basic secured WMS/WFS can be loaded in the service registry but a user will get a HTTP Basic popup when this service is used in an application.

Add a proxy which sends requests with pre-emptive HTTP Basic Authorization header to the original service and streams it back to the client (based on ApplicationLayer, check authorization of course). Also check if the current ProxyActionBean for feature info and AttributeActionBean correctly work with secured services.

**Comment by mprins** [comment]
release 4.7.4 provided some bugfixes in the proxy bean
