### ISSUE TITLE
Solr configuration screen: getStore is undefined

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#281]
In console: Uncaught TypeError: Cannot read property 'getStore' of undefined --> makes the grid empty

**Comment by mprins** [comment]
Misschien op te lossen zoals in a276f6f7489df7aef014ee3a88acc68b0c947e58 (lijkt op dezelfde fout)

Verplaatsen van de externe script tag met `editsolrconfig.js` naar boven de andere script tag in `editsolrsource.jsp`

**Comment by mtoonen** [comment]
Lijkt niet fout te gaan, dank voor de tip!
