### ISSUE TITLE
Bug in geotools: emptyonline resource in getcapabilities fails

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#289]
~~https://jira.codehaus.org/browse/GEOT-3255?jql=text%20~%20%22onlineresource%20empty%22~~

since codehaus shut down this is now at: https://osgeo-org.atlassian.net/browse/GEOT-3255

**Comment by mprins** [comment]
Closing this, as in 0122cfc9e477a8d7865b54835129e44e3c0f49a7 we upgraded the WFS module which should not have this bug.

**Comment by mprins** [comment]
reopening because of #524

**Comment by mprins** [comment]
see also: https://osgeo-org.atlassian.net/browse/GEOT-5458

**Comment by mprins** [comment]
This will be fixed when we upgrade to GT-WFS-NG which requires java 8
