### ISSUE TITLE
voorgrondkaartlaag wordt niet getoond voor deel van scherm

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#302]
indien een paneel weggeklapt kan worden en dit ook daadwerkelijk staat weggeplakt, dan wordt de voorgrondkaart niet getoond voor het deel dat onzichtbaar zou zijn als het paneel niet is uitgeklapt. Gek genoeg wordt de achtergrondkaart wel goed getoond.

**Comment by mtoonen** [comment]
Kan het niet reproduceren
