### ISSUE TITLE
Variable appConfigJSON can be empty resulting in JS errors

### ISSUE THREAD

**Issue by geertplaisier** [flamingo-geocms/flamingo#308]
Apparently the appConfigJSON var can be empty which results in JS errors in the configPage.jsp. In commit 853f6286ee624475a0aeec1006a46210614c2191 I added an if statement to check for emptiness which resolves this issue but it might occur in more places? It might also be better to resolve this issue in the backend.

**Comment by mtoonen** [comment]
Doesn't appear to happen anywhere else, except in app.jsp. But when it's empty there, there is something else wrong. Closing.
