### ISSUE TITLE
Do not serve feature info when map is out of scale

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#326]
The map should not serve feature info when the layer is out of scale and thus not visible. The ToC knows when the layer is out of scale so a check must be possible.

**Comment by mtoonen** [comment]
@NiekBouma en @cvanlith volgens mij is dit al zo: https://github.com/flamingo-geocms/flamingo/commit/c48a75654ecfe8bdb354ce01212d48762f40b729
Kunnen jullie dit bevestigen?
