### ISSUE TITLE
TOC doesn't expand/collapse subfolders when left/right margin is closable

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#350]
Example:
http://tte-geoportaal.mr-hosting.nl/viewer/app/HEMbrugPlanning_test
"Achtergrond" is not collapsible .

First estimate cost of fixing.

**Comment by jaccowanders** [comment]
Finally, I managed to reproduce the bug. The problem with the TOC arises when the function ”attributen Lijst” (AL) is added into the Layout.  Once I delete this function from the layout all applications are working fine (collapsible menu’s/subfolders)
