### ISSUE TITLE
Configure automatic checking of layers / levels when added trough SelectionModule

### ISSUE THREAD

**Issue by geertplaisier** [flamingo-geocms/flamingo#353]
You must be able to configure whether to automatically check layers/levels when added through the SelectionModule. Only the first layer of the layers that are added is checked.

Configuration options are: Always, Never, Only background
Default is Always.

**Comment by mtoonen** [comment]
Shouldn't the default be "never", to accommodate backwards compatibility?

**Comment by geertplaisier** [comment]
Actually this already worked for layers and appLayers, but not for levels. For layers and appLayers the default behavior was to check the added layers so 'always' seemed like a better default for backwards compatibility.

**Comment by mtoonen** [comment]
Ok, in that case: good call!

**Comment by geertplaisier** [comment]
This is not working properly for background layers yet. Behavior for the configuration options should be:

Always: check all layers that are added
Never: do not check layers that are added
Only background: do not check layers that are added and only check the first added background level (other background levels should be unchecked)
