### ISSUE TITLE
specifying color or label on creating feature fails

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#382]
eg. using the following code (from the merge control) and adding the feature to a vectorlayer I would expect the feature to have that specific colour and label but it just has the default.

```
var feat = Ext.create("viewer.viewercontroller.controller.Feature", {
                    wktgeom: wkt,
                    id: feature.__fid,
                    // TODO dit lijkt niet te werken..
                    label: (this.mode == "selectA") ? "A" : "B",
                    color: (this.mode == "selectA") ? "#FF0000" : "#00FF00"
                });
```

it seems that style is always overwritten in https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/webapp/viewer-html/common/viewercontroller/openlayers/OpenLayersVectorLayer.js#L197

**Comment by mtoonen** [comment]
Fixed in e95bd1f87aecf4a514935724482fc7992a94548f
