### ISSUE TITLE
BufferObject adds listener for ON_LAYERSELECTOR_CHANGE but doesn't handle the event

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#385]
The BufferObject control listens for ON_LAYERSELECTOR_CHANGE but doesn't handle the event (it doesn't have a `layerChanged` function and it doesn't have a superclass that does)

  - [viewer.components.BufferObject](https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/webapp/viewer-html/components/BufferObject.js#L99) line 99

**Comment by mtoonen** [comment]
Is bufferobject still used? I thought that it is replaced by BufferImage.

**Comment by mprins** [comment]
it still exists? I noticed this working on 604515290bd7da9a1ffb760411ce879d95b11a23

**Comment by mtoonen** [comment]
Fixed in branch impr/remove-unused-components
