### ISSUE TITLE
Related featuretypes in feature info

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#390]
When you do a featureinfo on a layer with a joined featuretype, only the attributes from the first featuretype (ie. the featuretype directly linked to the layer) are shown

**Comment by mtoonen** [comment]
I think you mean related featuretypes? Joined featuretypes are already shown.

**Comment by KJLammers** [comment]
Yes, it should be 'related featuretypes'

**Comment by geertplaisier** [comment]
See #545
