### ISSUE TITLE
AttributesActionBean uses attributename for attributesToInclude. Should use attributeId

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#411]
When a featuretype has a relates featuretype with attributenames that have the same name, it will incorrectly select the attribute(s).
@mprins : In snappingcontrol this is used for retrieving the geometry: &graph=true&attributesToInclude=geomAttribute: OpenLayersSnappingController r144.

Problems with a change to attributeId? This will result in a change in FeatureToJson r261: 
graph && attributesToInclude.contains(ca.getAttributeName() becomes:
graph && attributesToInclude.contains(ca.getId()

**Comment by mprins** [comment]
that's OK with me.

**Comment by mtoonen** [comment]
Fixed in #412
