### ISSUE TITLE
Null pointer exception bij downloaden Attributenlijst naar Excel 

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#422]
http://ibis.b3p.nl/app/VRBZO?name=VRBZO 
in deze applicatie (en ook in VRBZO/v2) krijg je een foutmelding als je de attributenlijst opent, je bedrijventerrein kavels of bedrijventerrein begrenzing kiest, het bestandsformaat op Excel zet en op Download drukt.

{
    "message": "Fout bij ophalen features: java.lang.NullPointerException",
    "success": false
}

Bij bestandsformaat 'Shapefile' krijg je dit ook, bij bestandformaat 'csv' niet.
Bij brandkranen krijg je dit nooit (deze heeft een andere bron dan kavels en bedrijventerreinen)

zie ook https://github.com/flamingo-geocms/flamingo/issues/294

**Comment by mprins** [comment]
of #339

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
