### ISSUE TITLE
Overviewmap is squashed when using static image

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#430]
Using an overview map based on a static image, the overview is squashed, it seems the image has width/heigth css attributes that are wrong (at least width is)

![image](https://cloud.githubusercontent.com/assets/1165786/10020807/253a401e-6145-11e5-88c7-f87cbe0a2eb0.png)

see: http://ibis.b3p.nl/app/IBIS2/vvjaap

I'm curious if someone touched css class `img.olTileImg`?

@mtoonen can you provide that link to the working version (luchtkwaliteit?)

@geertplaisier any ideas?

## for reproduction:

config param | value
------------ | -------------
Breedte | 150
Hoogte | 110
Positie | Rechtsonder
URL | http://flamingo.prvgld.nl/print/Overzichtskaart.png
lo-x | 123776
lo-y | 408506
rb-x | 258718
rb-y | 506174

**Comment by geertplaisier** [comment]
Not sure how to fix this. This happens somewhere in the OpenLayers code. From viewer.viewercontroller.openlayers.components.OpenLayersOverview a OpenLayers.Layer.Image is created. There something happens with aspectRatios, I guess that is where you should look.

**Comment by mprins** [comment]
it works OK in old version eg. http://flamingo.prvgld.nl/viewer/app/Asbest

**Comment by mprins** [comment]
It seems that the overview is initialized with the maxBounds as extent (left: 7700 ,right: 280000, top: 620000, bottom: 304000) and not the configured extent (the numbers above)
