### ISSUE TITLE
SelectionModule/search: can't find maplayers

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#449]
Maplayers can not be found on search. It seems that only maps are found.

**Comment by mtoonen** [comment]
in what tab? In the first tab that's correct

**Comment by andreweijmer** [comment]
In the second tab "kaartlagen". First tab is at the moment correct. 
In the to build version should it also be possible to find a maplayer on search in the first tab.

**Comment by mtoonen** [comment]
Second tab searching isn't for searching layers, but the services.
