### ISSUE TITLE
Alternative legendgraphic does not show

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#450]
Version 4.5.6
The alternative legendgraphic cannot be used.
Looking at the sourcecode it adds a scale parameter to the url. 
http://gisopenbaar.overijssel.nl/flamingo/basis/legenda/B1/gemeentegrens_vlak.png&SCALE=380976.58368000004 

When i manually remove the scale parameter in the url it works
http://gisopenbaar.overijssel.nl/flamingo/basis/legenda/B1/gemeentegrens_vlak.png

**Comment by mtoonen** [comment]
Should be a ? instead of a & in this case.

**Comment by andreweijmer** [comment]
Ok, but I can not change these parameters.

**Comment by mtoonen** [comment]
No, correct. It was more of a reminder for the dev who will fix it :)
