### ISSUE TITLE
Attributes: No export to shapefile

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#451]
ver.4.5.6
export to shapefile does not work.
{
    "message": "Fout bij ophalen features: org.geotools.data.DataSourceException: Cannot create a shapefile whose geometry type is class com.vividsolutions.jts.geom.Geometry",
    "success": false
}

**Comment by mtoonen** [comment]
Geometrytype is not known: it is the generic Geometry, instead of the subclass point, line or polygon (or the multi variant of them).  Can you try a different source, where the geometrytype is correct?

**Comment by andreweijmer** [comment]
I have tried several applayers. Not one is downloadable. For some applayers i get a different message: {
    "message": "Fout bij ophalen features: java.lang.NullPointerException",
    "success": false
}

I must notice that we have the featureclasses stored in a postgres database insead of Oracle.

**Comment by mtoonen** [comment]
@andreweijmer can you check if the latest version of flamingo fixed this issue? Some improvements were made which I expect will fix your problem

**Comment by NiekBouma** [comment]
I also get this error in the Venray flamingo4 (version 4.7.5).

**Comment by NiekBouma** [comment]
This also happens in http://venray.flamingo4.nl/viewer/app/BGT/v2 which is version 4,75.: Null Pointer exception
In http://venray.flamingo4.nl/viewer/app/WOZ/v2 on the Percelen kadaster map you get the error:
'Fout bij ophalen features: org.geotools.data.DataSourceException: Cannot create a shapefile whose geometry type is class com.vividsolutions.jts.geom.Geometry'

**Comment by mtoonen** [comment]
Fixed: now for each feature the geometrytype is determined, and written to it's own shapefile (so a shapefile for polygons, points and linestrings).
