### ISSUE TITLE
SQL-filter in url does not work

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#453]
ver.4.5.6
In the past we could filter on a applayer on startup of the viewer. This does not work anymore.

http://gisopenbaar.toverijs3.nl/viewer-geodata/app/advanced/v1?cqlFilter=GEMNAAM=%27Zwolle%25%27&selectionLayerId=5053

**Comment by mtoonen** [comment]
See also #243. @fsteggink/@f-steggink created this functionality, but I had some issues, so it couldn't be merged.

**Comment by andreweijmer** [comment]
Hoi Meine,

Houdt dit in dat deze functionaliteit niet meer werkt en ook niet meer gaat werken. Wij willen deze functionaliteit eind van dit jaar toch wel beschikbaar hebben. Wat is de weg te gaan?

M.vr.groet,

André Weijmer
Beleidsmedewerker Uitvoering (GIS)

Beleidsinformatie voor Cijfers, Kaarten en Onderzoek
Provincie Overijssel
Team Beleidsinformatie
Postbus 10078
8000 GB Zwolle

Telefoon 038 499 9703
 Alle kaarten van Overijssel bekijken? Kijk op de www.atlasvanoverijssel.nl<http://www.atlasvanoverijssel.nl/>


Van: Meine Toonen [mailto:notifications@github.com]
Verzonden: woensdag 21 oktober 2015 14:00
Aan: flamingo-geocms/flamingo
CC: Weijmer, AM (Andre)
Onderwerp: Re: [flamingo] SQL-filter in url does not work (#453)


Closed #453<https://github.com/flamingo-geocms/flamingo/issues/453>.

—
Reply to this email directly or view it on GitHub<https://github.com/flamingo-geocms/flamingo/issues/453#event-441411333>.

****************************************************************
Het is mogelijk dat er tijdens het transport van dit bericht fouten
zijn ontstaan zodat het bericht onjuist is overgekomen.
Hiervoor kunnen wij geen aansprakelijkheid erkennen. Indien er sprake
is van een besluit zal de vastgestelde versie per post aan u worden
toegezonden.
Indien er sprake is van overige mededelingen adviseren wij u om bij
twijfel over de juistheid of volledigheid contact met ons op te nemen.
****************************************************************
