### ISSUE TITLE
Graph: WFS does not work

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#454]
The Graph option does not work ona WFS source

**Comment by mtoonen** [comment]
Can you provide an example? What are the errors?

**Comment by andreweijmer** [comment]
message:
{
    "message": "Fout bij ophalen features: org.geotools.data.DataSourceException: Cannot create a shapefile whose geometry type is class com.vividsolutions.jts.geom.Geometry",
    "success": false
}

![image](https://cloud.githubusercontent.com/assets/9362360/10636311/4e8998a4-77ff-11e5-8fb1-8e41d964123c.png)

**Comment by mtoonen** [comment]
Wrong issue? Think this belongs to #451

**Comment by andreweijmer** [comment]
There are no errors. The graph will not show after pacing a point on the map. Settings in layout are:
![image](https://cloud.githubusercontent.com/assets/9362360/10637938/a0a4f800-7808-11e5-82b8-056cb684b507.png)

url= http://gisopenbaar.toverijs3.nl/viewer-geodata/app/advanced/v1

**Comment by mtoonen** [comment]
invalid: tested with geoserver and deegree: works.
