### ISSUE TITLE
Twitter component

### ISSUE THREAD

**Issue by ekopp** [flamingo-geocms/flamingo#467]
How should I configure the Twitter component?
I only see 'Name' and 'Value', but nothing when I open the webmap. Do I have to give in a Twitter account somewhere?

**Comment by mprins** [comment]
The Flamingo Twitter component was built for Twitter API v1.0 which has been shut down by twitter, so it no longer works.

Twitter's (new) v1.1 API requires authentication and authorisation using OAuth of all API requests, basically a rewrite of the component is required to make it work.
