### ISSUE TITLE
Toevoegen pop up button leidt tot een foutmelding

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#473]
In flamingoupdate: when I add the pop up button to the layout with available components, I get a yellow triangle at the bottom of the application (RTL/v3). When I click on the triangle, I get the following error message: 
Error creating component with className viewer.components.PopupButton: error TypeError: Cannot read property 'popupWin' of null with config [object Object]

**Comment by mtoonen** [comment]
Klopt, was geen component in popupwindow regio geconfigureerd.
