### ISSUE TITLE
Legend does not show pictures in Chrome or Firefox

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#482]
When turning on some map layers and clicking on the legend tab, in Chrome no pictures are shown (like dots, arrows, etc) but white boxes. In Firefox not even the boxes are shown. 
In IE or Edge the pictures are shown correctly
![geen afbeeldingen in legenda in chrome of firefox](https://cloud.githubusercontent.com/assets/14270448/11563071/1c904df8-99d2-11e5-9312-03ec82443786.PNG)

![firefox legenda](https://cloud.githubusercontent.com/assets/14270448/11563075/2521c8a2-99d2-11e5-8393-a9fe34197f0d.PNG)

**Comment by geertplaisier** [comment]
Fixed in e8f61188258d248bbdd3fdeb4cde735bc40bd7bb
