### ISSUE TITLE
Featureinfo control: spinner disappears before all layers have responded

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#487]
Currently the spinner of the feature info disappears when the first layer responds (irrespective of returning features) 

Consider the following case:
  -  a map with two layers:
     - a sparsely populated layer of buildings (response time ~ 500ms)
     - a layer of parcels (response time ~1500 ms)
  - a feature info control with spinner

When feature info is requested on both layers the spinner starts;
when the [empty] info on the buildings return the spinner is removed but no popup is added; 
("nothing happens" for the user, it seems no info was returned - lets klick again!)
after some time the info on the parcels returns, but the user may have already clicked again.

I can think of several "solutions"

  - wait until the last request has returned (or timed out) before removing the spinner
  - wait for the first response that has a non-empty array of features
  - do nothing
  - educate the user... :bomb: 
  - ...

@geertplaisier We should take a look at this

**Comment by geertplaisier** [comment]
Added the first proposed solution to the master (c423170a9e13ce887aa84f33b258ad0d82cd88c1). The spinner is now hidden after all the requests are done.

Another solution worth discussing would be to always show the maptip/balloon, show a loading message inside the maptip and show a message like "no items found" when all requests are done and no results are returned. This way the user is sure he/she has clicked, gets immediate feedback and also sees when all requests are done and what the reason is for having no results.

**Comment by mprins** [comment]
@mtoonen Should we just close this and accept the changed behaviour "wait until the last request has returned (or timed out) before removing the spinner" as the proper fix (and it will be in the upcoming 4.6.0) ?

**Comment by mtoonen** [comment]
Yeah, I think this is the best behaviour. However, precautions must be taken when requests fail, so there will be no infinite spinners. If that is the case, close it.

**Comment by mprins** [comment]
hmm it seems the error handler created in the MapTip is never propagated to the request manager, 

see: https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/webapp/viewer-html/components/RequestManager.js#L46 :
```javascript
...
    },
    request: function(id, options, radius, layers, callback, failure) {
        var me = this;
        if (this.previousRequests[id] === undefined) {
            this.previousRequests[id] = new Object();
            this.previousRequests[id].requests = new Array();
            this.previousRequests[id].total = 0;
            this.previousRequests[id].done = 0;
            this.cancelPrevious(id);
        }
        var extraParams = {
            requestId: id
        };
        for(var i = 0 ; i < layers.length;i++){
            var request = this.featureInfo.layersFeatureInfo(options.coord.x, options.coord.y, radius, [layers[i]], extraParams,function(data){
                me.responseReceived(data[0].requestId);
                callback(data);
            }, this.onFailure,me);
```
where it is set to an undefined (there is no `onFailure` function in RequestManager), I think this should be set to the `failure` argument of the `request` which will probably land us in scope hell
