### ISSUE TITLE
components are re-ordered in "Leftmargin top"

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#495]
> EKU 11/12 zojuist verschenen: in de beheervenster, in 'layout met beschikbare componenten' in 'leftmargin-top', is de volgorde verkeerd. Ik zet de componenten in de goede volgorde zet en sla dit op. Als ik nu weer het scherm 'layout met beschikbare componenten' open, dan wordt de volgorde van componenten gereset en moet ik weer de volgorde goedzetten. Dit is reproduceerbaar en niet wenselijk.

**Comment by mprins** [comment]
this was reported against the geotools14 branch

**Comment by NiekBouma** [comment]
Niet reproduceerbaar, de componenten blijven op de nieuwe plek staan.

**Comment by mprins** [comment]
closing, have not been able to reproduce either.
