### ISSUE TITLE
identical named attribute field values of joined source overwrite values of source

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#497]
In the following case the value of the joined attribute overwrites the value of the parent.
- one attribute source `kavels` with fields `terreinid` and `workflow_status`
- one attribute source with fields `terreinid` and `workflow_status`

A join is made on `terreinid` (kavels left, the other source on the right), for the feature info the `workflow_status` is checked for both sources in the **Boomstructuur met kaarten** > **Attributen** of the map layer.

There is a record in `kavels` where `workflow_status='bewerkt'` that matches to a record in the other source `workflow_status='definitief'`

A featureinfo request/response will show the value "definitief"  (and only one workflow_status)

**Comment by KJLammers** [comment]
confirmed for version 4.5.6, it doesn't matter whether the joined attribute comes from a table or a view

**Comment by mprins** [comment]
this happens in the geotools14 branch as well

**Comment by mprins** [comment]
Maybe we should prefix the joined attributes with the name of the featuretype?
