### ISSUE TITLE
Refactor JTS dependencies

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#500]
Geotools 14.x comes with JTS 1.13 [excludes the xercesImpl](https://github.com/geotools/geotools/blob/14.x/pom.xml#L742), we probably don't need JTS as a direct dependency anymore.

**Comment by mtoonen** [comment]
I see that in viewer/pom.xml we do have a dependency to JTS, but we have excluded xerces. We do use it, but I think we can safely update it.
