### ISSUE TITLE
Solr sources cleared after updating attribute source

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#501]
When a user updates an attributesource in the data registry some sources in the Solr configuration have their attributes reset. A definitive cause has not yet been determined nor is it clear why some are reset, and others are not. What appears to happen is that the order of attributes is shuffled after updating. This probably causes the problem for the Solr sources, but why this happens is unclear. 

A similar problem (and quite possibly the same) exists with the Join/relates, which are also reset after updating an attribute source

**Comment by KJLammers** [comment]
this goes for version 4.5.6 and higher

**Comment by mtoonen** [comment]
Were the attributes in the source (WFS/database) updated? I think flamingo deletes/inserts the attributes, so the attributes in the solr configuration page (and join/relate) will be truncated.

**Comment by KJLammers** [comment]
They were not updated. Even though nothing changed in the JDBC database the attributes were shuffled. 

Maybe related issue:
After updating an attributesource Flamingo4 shows you how many featuretypes were altered and how many were unchanged. In this case Flamingo4 reported 5 changed featuretypes. The Service User Matrix however showed 6 changed featuretypes.

**Comment by mtoonen** [comment]
@matthijsln 
When updating a featuresource, where at least one attribute is changed/removed/added, all attributes are added to the flamingo db again. The previous attributes however, still exist. 
This poses a problem for SolrConfigurations, and Join/relates: those configurations still point to the old attributes.
Can you help me fix this?
