### ISSUE TITLE
The first component in the Top menu is always active as default

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#506]
The first component in the Top menu is always active as default. So if you want the Identify to be active without having to click on it, you must position it as the first component in the Top menu. 
Suggestion: add a tick box in the components' Edit-screen, to make it the default active component.

**Comment by mtoonen** [comment]
This is as designed. Is this a suggestion from a customer?

Op do 31 dec. 2015 09:10 schreef NiekBouma <notifications@github.com>:

**Comment by NiekBouma** [comment]
Yes, this came to light when I was working on the project for PZH.
