### ISSUE TITLE
Detect GeoServer and check 'use intersect instead of dwithin' automatically

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#516]
GeoServer does not support dwithin, without checking this option in the service registry (which is easy to forget to do for GeoServer services) feature info / map tip don't work.

Look for GeoServer specific vendor capabilities elements in WMS GetCapabilities and automatically enable this option. Better yet look explicitly for DWithin being supported (if possible).

**Comment by geertplaisier** [comment]
Duplicate of #30
