### ISSUE TITLE
It is possible to zoom outside the maximum extent

### ISSUE THREAD

**Issue by geertplaisier** [flamingo-geocms/flamingo#526]
In my application settings I have set a maximum extent, but it is possible to zoom outside of this max extent.

**Comment by mprins** [comment]
using scroll-zoom / zoombar, eg. zoomToExtent behaves correctly

**Comment by geertplaisier** [comment]
Won't fix this issue, this is default OpenLayers behaviour. See http://dev.openlayers.org/examples/restricted-extent.html

It is possible to zoom beyond the max extent but it is not possible to pan beyond the max extent and it is also not possible to zoom to a different location.
