### ISSUE TITLE
flamingo installation, tomcat not working (404)

### ISSUE THREAD

**Issue by gisveld** [flamingo-geocms/flamingo#532]
I am new to Flamingo. I try to install the Flamingo viewer. For this I use the following guide: https://github.com/flamingo-geocms/flamingo/wiki/Install. I feel I have done well all the steps but the localhost / admin viewer displays a 404 error.Below is a list of my system features and downloads:

• Windows 10
• Java is up to data
• PostgreSQL 9.5 (database was created correctly)
• Tomcat 8.0 (Windows installer service)

Tomcat is working properly right after the download. But when i make the changes in the server.xml etc. its not working anymore. 

What steps do I run in Tomcat:
• 0. The latest WAR files. I have stored them in the folder "web apps" (it is true that there are two folders are created automatically, when you put these files in the "webapp-folder"?)
• 1. I have set the datadirectory  in the server.xml file 
• 2. Java, Tomcat, PostgreSQL are installed fine
• 3. created a database in PostgreSQL
• 4. When properly set up Tomcat to be downloaded are two JAR files. However, the download includes 3 files (postgis_1.4.0SVN, postgresql-9.0-801.jdbc4, javax.mail). Therefore, it is not clear which is 2 in the must be put in the lip'-folder, and which files in the' endorsed'-folder. I therefore put all three JAR files in both folders. Is that a problem?
• 5. I have the 'endorsed' directory created directly into the Tomcat directory. Is this correct?
• 6. The specified script I added to server.xml 
• 7. The WAR files are stored in the 'webapps'-folder (see also 0)
• 8. When I start I get a 404 message and there will be created a number of logs to the viewer admin. (for logs see attach)

I like to hear how I can solve this.

Hein Bauke Visser
GISveld

**Comment by mtoonen** [comment]
Editted the numbers for clarification:
0. Yes, it's correct: the .war files are unpacked in the webapps directory
1. You must set the data directory in either the web.xml or the context.xml
4. Hmm, might be a problem, never tried it :). You can put the files in tomcat/lib folder
5. Yes, it's correct, but not necessary. See 4
6. Did you restart tomcat after adjusting the server.xml?
8. Logs are not attached, can you post them?

**Comment by gisveld** [comment]
Thank you. Its working now.

Ad 1. Maybe the installation-text is a little bit confusing. I looks like you have to set the datadirectory in one of the 3 files, but only web.xml or context.xml is working.
I also made a mistake with the creation the password of the PostgreSQL database. You have to choose 'secret', and not create a password of your own choice.

**Comment by mtoonen** [comment]
Ok, good that you got it working.
ad 1: You're right, it is possible to put it in the server.xml, my bad.
