### ISSUE TITLE
Remember checked layers in TOC for each individual user

### ISSUE THREAD

**Issue by geertplaisier** [flamingo-geocms/flamingo#538]
Use Cookie/LocalStorage to remember which layers (default layers, not layers added by SelectionModule?) where checked by the user so this can be restored when reloading the application.

**Comment by geertplaisier** [comment]
See #f73e4a84e32b8140a55f1a0d681bfbb2f27e8d7e

**Comment by geertplaisier** [comment]
See f73e4a84e32b8140a55f1a0d681bfbb2f27e8d7e

**Comment by NiekBouma** [comment]
Does not work as requested yet. For instance in the 'Solparc -  Supermarkten en apothekers' application, if no layers are selected in 'het Startkaartbeeld', and the user selects the 'Voorzieningen'-layer, after pressing <F5>  the 'Voorzieningen-layer' is not active.

**Comment by geertplaisier** [comment]
The mentioned application was not configured correctly. You have to configure the TOC component to remember the checked layers (Aangevinkte kaartlagen onthouden). When I enabled this option everything works as expected. @NiekBouma could you please verify if everything works as expected now?
