### ISSUE TITLE
Extend possiblities of the LayerSelector component

### ISSUE THREAD

**Issue by geertplaisier** [flamingo-geocms/flamingo#540]
The LayerSelector component is used in a lot of components. Currently this selector is displayed as a dropdown selector. It would be nice to configure the layout of the LayerSelector to choose between dropdown selector and tabs. For example in the Attributelist it would be useful to show the LayerSelector as tabs to provide easy switching between sources.

**Comment by geertplaisier** [comment]
See #586

**Comment by mprins** [comment]
nog ff testen aub

**Comment by NiekBouma** [comment]
Tested, works as requested.
