### ISSUE TITLE
Date field of ArcGIS REST service is not visible in Flamingo4 Viewer

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#558]
B3Partners/flamingo#11

**Comment by geertplaisier** [comment]
Date field is of type: esriFieldTypeDate
Example response from ArcGIS for this field: 1432166400000

In the viewer the response from Flamingo on GetFeatureInfo does not contain this field at all

**Comment by mprins** [comment]
those be epoch milliseconds since 1-1-1970 in GMT, this format was changed in arcgis server since 9.3.1 (regular time/date with timezone) to 10

**Comment by mprins** [comment]
We're using the Geotools converters to convert from the reponse type (Long) to the target type for the feature (Date); however this is not a supported conversion in TemporalConverterFactory, we can add a custom converter or get it added to Geotools.

see: https://sourceforge.net/p/geotools/mailman/message/34966190/

**Comment by mprins** [comment]
wordt opgelost met geotools/geotools#1147 (of geotools/geotools#1146)

**Comment by mprins** [comment]
My patches were merged upstream, so this will just need to wait for a new release of Geotools (either 14.4 or 15.0) to be used in Flamingo.

**Comment by mprins** [comment]
geotools/Geoserver release schedule is available at: https://github.com/geoserver/geoserver/wiki/Release-Schedule
