### ISSUE TITLE
Unticking the boxes in a component layout 

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#562]
If you 'untick' the boxes in a component at 'user can change the position of the popup' or a 'user can change the size of the popup' does not lead to a fixed position or size of the popup. The user can still change both the position and size of the popup. With feature-info in the first screen the position and size can not be changed not matter if the boxes are ticked or not. This should also be possible.

**Comment by NiekBouma** [comment]
With feature-info the first screen the position and size can not be changed not matter if the boxes are ticked or not. This should also be possible.

**Comment by mtoonen** [comment]
No, this is by design. The balloon size can be changed through the input fields, but the user can never change them. The user _can_ change the popup you get after clicking the "meer" link.

**Comment by geertplaisier** [comment]
Apparently this is an issue for every component, according to @NiekBouma it is now possible to always resize the popups, regardless of what is set by the user.

The FeatureInfo case is a special case, this issue is indeed not applicable to FeatureInfo
