### ISSUE TITLE
In solparc Meldingen application the feature source can not be edited

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#563]
In solparc Meldingen application when you try to edit the map layer you get the message:
'Feature source does not support editiing' while it is a database-source.

**Comment by mprins** [comment]
permissions in the database may prevent editing

**Comment by mtoonen** [comment]
Missing important information: url to application. Also solparc is gissuite, this is the flamingo github.
But - if it's flamingo - it can be that the table doesn't have a primary key.

**Comment by NiekBouma** [comment]
It is Flamingo4.b3p.nl: http://flamingo4.b3p.nl/viewer/app/Solparc%20-%20Meldingen%20openbare%20ruimte/v1

Feature source is: beurs_gisdata on x18, table 'Meldingen'. The table has a primary key.
No editing is allowed.

**Comment by NiekBouma** [comment]
Editing is possible now. It is a matter of configurating the edit tool well. For instance, for entering a new notification the status of the notification should be 'Nieuw'. When you leave that out, the notification is saved in the database, but no image is shown on the map for the notification.
