### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#566]
If a component's screen is too small to show all the elements a scroll bar on the right hand side should emerge to navigate to the elements that are not visible at first.

**Comment by NiekBouma** [comment]
in flamingo4.b3p.nl, if the resolution of the screen is too small in the printing component for instance, a scroll bar on the right hand side should make elements like buttons or text fields visible.

**Comment by geertplaisier** [comment]
@NiekBouma Please check if this is fixed in the latest snapshot release. If the problem is fixed, please close this issue.

**Comment by NiekBouma** [comment]
the problem is fixed. the headers and horizontal scroll bar remain visible at all times.
