### ISSUE TITLE
it should be possible In the edit-tool to switch off the 'edit' ('bewerk') button 

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#578]
### Where?
in the viewer-admin in the layout with components 

### What happened
the edit button is visible

### What did you expect?
it should be possible to switch the edit button off, like the 'Copy', 'Delete' and 'New' button. When there is only one button selected, that button should automatically be active. So, it there is only a 'New' button, the user should not have to press the 'New' button. Reason for the change: If you start typing information in the fields and then you press the 'New' button, all the information is gone.

### Reproduce
open the edit-tool in the viewer.

### Version
4.7.0. Snapshot

### URL
http://flamingo4.b3p.nl/viewer/app/Solparc%20-%20Meldingen%20openbare%20ruimte/v1

**Comment by mprins** [comment]
Clicking the "New" button is required to switch the map into "digitizing"  mode

**Comment by NiekBouma** [comment]
in other words: to be able to draw a point, line or polygon.

**Comment by cvanlith** [comment]
form visible after selection of action button, when only one action configured then action is automatically active, buttons should clearly indicate which action button is selected.

**Comment by NiekBouma** [comment]
Tested, works as it should now
