### ISSUE TITLE
Modify or delete a certain group

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#580]
### Where?
flamingo4.b3p.nl/Viewer-admin/User management/User groups

### What happened
I tried to modify or delete the group 'Frank's Posse'.  This group was made during a training.

### What did you expect?
Modify: a screen opens to modify the groups details
Delete: the group is deleted.

Other groups can be modified or deleted. 
### Reproduce
Go to Viewer-admin/User management/User groups/click on 'Modify' or 'Delete' in the row where Frank's Posse is located. Nothing happens. The log doesn't show anything.

### Version
4.7.0. Snapshot

### URL
http://flamingo4.b3p.nl/viewer-admin/action/group/default#

**Comment by mprins** [comment]
A javascript error occurs after clicking on "Bewerken" or "Verwijderen":

```
Uncaught SyntaxError: missing ) after argument list
```
