### ISSUE TITLE
Add possiblity to configure grouping and order of attributes

### ISSUE THREAD

**Issue by geertplaisier** [flamingo-geocms/flamingo#584]
It should be possible to configure grouping and order of attributes. This should be done when configuring an application layer.

This order and groups can then be used in attributelist, edit component, feature info - more, etc.

**Comment by mtoonen** [comment]
@geertplaisier The folders aren't being restored when viewing the tree

**Comment by geertplaisier** [comment]
Merged in master https://github.com/flamingo-geocms/flamingo/pull/655

**Comment by mprins** [comment]
closing as this was merged in master
