### ISSUE TITLE
Update geotools to version 15 (or 16)

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#602]
Requires java 8, so schedule it for version 5.

**Comment by mprins** [comment]
By that time Geotools 16 will probably have a stable release

**Comment by mprins** [comment]
preferably this should be combined with upgrading to GT-WFS-NG; it seems the naming issues we ran into earlier and needed to repair #524 are mostly fixed in 16 (see: https://osgeo-org.atlassian.net/browse/GEOT-4883 and geotools/geotools#1241)

**Comment by mprins** [comment]
regarding WFS-NG; this should be a proper drop-in replacement; see the notes at https://github.com/geotools/geotools/wiki/WFS-to-WFS-NG-upgrade
