### ISSUE TITLE
"Open viewer" link fails when viewer is not deployed as default (eg. viewer is ROOT)

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#607]
### Where?
viewer-admin: "Kies applicatie" page

### What happened
application links point to `/viewer/app/...` but correct url are `/app/...` because viewer.war is deployed as ROOT.war

### What did you expect?
Links should be correct

### Reproduce
deploy viewer.war as ROOT application in tomcat

### Version
4.7.1-SNAPSHOT

**Comment by mtoonen** [comment]
in context.xml/server.xml/web.xml you have to set your viewer.url parameter, that should do the trick.

**Comment by mprins** [comment]
OK, now that seems to fail when using a relative url like "/" though the backend response to the `/getGridData` call makes sense; see json snippet below:

```json
{
totalCount: 4,
gridrows: [
{
baseUrl: "/",
id: 23,
name: "filtertest",
owner: "",
baseName: "filtertest",
published: "Ja"
},
{
baseUrl: "/",
id: 20,
name: "ibis-remote",
owner: "",
baseName: "ibis-remote",
published: "Ja"
},
{
baseUrl: "/",
id: 7,
name: "master",
owner: "",
baseName: "master",
published: "Ja"
},
{
baseUrl: "/",
id: 22,
name: "publiek",
owner: "",
baseName: "publiek",
published: "Ja"
}
]
}
```

this gives the result `app/master` which is still incorrect

**Comment by mprins** [comment]
in [chooseApplication.js#84](https://github.com/flamingo-geocms/flamingo/blob/master/viewer-admin/src/main/webapp/resources/js/application/chooseApplication.js#L84)

we can see the following code 
```javascript
                            Ext.String.format('<a href="{0}/app/{1}{2}" target="_new">Open viewer</a>', record.get('baseUrl'), record.get('baseName'), (record.get('version') ? '/v' + record.get('version') : '')),
```
which does not take missing values in regard.

**Comment by mprins** [comment]
Using an empty string for `viewer.url` works
