### ISSUE TITLE
Feature changes position when panning the map

### ISSUE THREAD

**Issue by jswis** [flamingo-geocms/flamingo#615]
### Where?
Viewer, panning on the map

### What happened
When zoomed in to a feature and then panning the map the feature moves position according to the basemap.

- I tried different basemaps from different sources.
- I tried different features from different sources and different types. I tried it with polygons and with points.

### What did you expect?
Feature should be at fixed position and should move in accordance to the basemap.

### Reproduce
 - Create a flamingo application with a basemap and a polygon/point layer.
- Zoom to a polygon/point
- Pan the map
- Observe the polygon/point and watch it "jump" around on the basemap. (See screenshots for an example.)
![1](https://cloud.githubusercontent.com/assets/9654315/16196077/b937ab70-36fc-11e6-9cb0-9cb830d628b5.png)
![2](https://cloud.githubusercontent.com/assets/9654315/16196078/b93a0cd0-36fc-11e6-9bb6-8ecb485c33f1.png)

### Version
I tested it with 2 versions:

- Version: 	4.5.2
- Version: 	4.7.0 

It happens in both versions

### URL
Where can we find an application which has the bug?
http://flamingo.zeeland.nl/viewer/app/pop2
For example zoom in to the hearth symbol at Borselle.

**Comment by mtoonen** [comment]
Hmm, never noticed that before. Can you try setting the resolution of the map to it's correct value? See if that helps.

**Comment by jswis** [comment]
@mtoonen Correctly setting the max extension of the application fixed the issue.

I thought I did do that before but I copy and pasted it.
For example i used lo-x as -285401.92 which after saving the application was stored as -28540192.
When using the dutch decimal separator (,) instead of the international one (.) it works.

If this is intended use or a bug is up to someone else to decide. But I believe it's confusing because in "het gegevensregister" I can only use the "." as a decimal separator. For example:
-285401.0,22598.0,595401.0,903401.0 since the comma is used to separate the coordinates.

Maybe I should copy and paste less and don't need a decimal separator at all :)

Anyway thanks for the fast reply and help.
