### ISSUE TITLE
org.hibernate.WrongClassException: when uploading a geo-service

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#616]
### Where?
In Gegevensregister in the viewer-admin of flamingo.b3p.nl/viewer-admin

### What happened
Tried tot upload a service as a test but the gegevensregister gave the following error back:
"Fout bij het laden van de service: org.hibernate.WrongClassException: Object with id: 4 was not of the specified subclass: nl.b3p.viewer.config.services.GeoService (Discriminator: )"

this was the case when uploading this service: 
http://tilecache.kaartenbalie.nl/tilecache.cgi/1.0.0/luchtfoto/  -> tiled service
http://kantoor.b3p.nl/cgi-bin/mapserv?map=/srv/maps/rsgb_brk_gouda_woningcorporaties.map&
-> wms

### What did you expect?
It should have uploaded without issues. Tried uploading both in a different viewer-admin and this worked without any glitches

### Reproduce
Upload either service in the gegevensregister in flamingo.b3p.nl/viewer-admin. 

### Version
4.7.0 

### URL
flamingo4.b3p.nl/viewer-admin/action/geoserviceregistry

**Comment by KJLammers** [comment]
[logfile of error.txt](https://github.com/flamingo-geocms/flamingo/files/325407/logfile.of.error.txt)

**Comment by matthijsln** [comment]
The cause was a null value in the protocol column of a geo_service record in the same category as the new service. Most likely cause inadvertently clearing the database record manually (it was the top-left most column, the first selected when opening the table)
