### ISSUE TITLE
Flamingo server freezes, after attaching aerial photo's

### ISSUE THREAD

**Issue by TABProvincieGroningen** [flamingo-geocms/flamingo#644]
### Where?
Both the viewer and viewer admin are no longer available/responding, after adding a layer with externally hosted aerial photo's.

### What happened
The services froze, after attaching aerial photo's to a map-layer. No maps were shown after activation.

### What did you expect?
That the maps would be shown, with the photo-layer.

### Reproduce
Go to Gegevensregister
Go to Services en Kaartlagen
Choose a Gegevensregister
Click right mouse button on preferred Gegevensregister
Choose Service toevoegen
Add the URL (in this case from our external provider)
Protocol: XML
Username/Password:  as provided by external provider
Click Service Inladen
Go to Kies een applicatie
Open a application
Open Boomstructuur met Kaarten
Choose a Sublevel
Add the Gegevensregister to the backgroundlayer of a map under Kaarten
Open the viewer
Choose the map, and choose the backgroundlayer you just added
Now everything freezes.

### Version
4.6.1 and 4.7.3

### URL
http://www.kaarten.provinciegroningen.nl

**Comment by mprins** [comment]
@TABProvincieGroningen which protocol? `XML` is not a valid mapping protocol (XML is for catching service exceptions), it must be one of:
- WMS
- ArcGIS MapServer (REST)
- ArcIMS
- Tiled

please send an email to support@b3partners.nl to have this resolved under your support contract; preferably with a screenshot of the service (Service .... bewerken) in the "Services en Kaartlagen" page and maybe service details

**Comment by TABProvincieGroningen** [comment]
Sorry, my fault: protocol is WMS, Exceptiontype is XML.\
I will contact B3Partners, to follow up.

**Comment by mprins** [comment]
OK, closing.

/cc @NiekBouma projectcode 16.0002

**Comment by mprins** [comment]
opgelost in de actuele versie 4.7.4
http://mantis.b3p.nl/view.php?id=5936
