### ISSUE TITLE
Identify popup is on top off detail information

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#647]
### Where?
viewer? identify popup
### What happened
The identify popup stays on top of detail information popup
### What did you expect?
Detail information popup shows on top off all.

### Reproduce
see url

### Version
4.7.1

### URL
http://gisopenbaar.toverijs3.nl/viewer-geodata/app/master_mashup_grondverkopen/v2016

**Comment by mprins** [comment]
this was restored in v 4.7.3 (4af5be7659a5aaa72834435e137be23510418827)
