### ISSUE TITLE
Incorrect Page and Feature counter Attributenlijst

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#650]
### Where?

Viewer, attributenlijst
### What happened

A layer has a WFS featuresource. I opened component 'Attributenlijst' and after loading the features of the layer, the Page and Feature counters are set to 100 and 1000 each. If you select an unreasonable page number (say, page 60, if you know there can only be 50 at the most), the attributenlijst will jump to the highest page possible.
![wfs featuresource](https://cloud.githubusercontent.com/assets/13237783/17206487/2eb8433e-54b0-11e6-848d-74c42eda0cb2.png)

If a layer has a DB as a featuresource, the page and featurecounter work just fine.
![jdbc database featuresource](https://cloud.githubusercontent.com/assets/13237783/17206488/2ebaa7a0-54b0-11e6-9499-9e5b1200ec9c.png)
### What did you expect?

I expected the counter to display the maximum number of pages and features of the WFS featuresource immediately after loading the features, like it does with a DB featuresource. 

If this is not possible, then it would be nice to see either a warning or explanation that the counter is not functional of working properly because the featuresource is a WFS and how to find the real number of pages and features.
### Reproduce

Go to http://flamingo4.b3p.nl/viewer/app/BAG%20(Testomgeving)/v1
Layers 'Gemeentes 2014' and 'Wijken 2014' have a WFS featuresource
Layer 'Buurten 2014' has a JDBC DB as a featuresource.
### Version

4.7.0
### URL

http://flamingo4.b3p.nl/viewer/app/BAG%20(Testomgeving)/v1

**Comment by mprins** [comment]
it may not always be possible to obtain a valid total count value because a WFS can have a maxFeatures  option enabled.

see also #452 and #392 
I'm not sure why those two issues were both closed. @mtoonen @geertplaisier ? I think this should be improved
