### ISSUE TITLE
Cyclorama Service URL uit GIS Suite kan niet geladen worden in Flamingo

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#688]
### Where?
Gegevensregister

### What happened
Bij laden service; ttp://venray.kaartenbalie.nl/cgi-bin/mapserv?map=/srv/maps/venray/Cyclorama.map& krijg ik de melding: 
Fout bij het laden van de service: org.geotools.ows.ServiceException: Error while parsing XML.
### What did you expect?
Dat de service ingeladen werd.

### Reproduce
Voeg een service toe, kies WMS als protocol en Exceptiontype Inimage.

### Version
4.7.5

### URL
http://venray.flamingo4.nl/viewer-admin

**Comment by NiekBouma** [comment]
* http

**Comment by mtoonen** [comment]
PEBKAC: the projection was not defined, so the getcapabitilies request yields an erroneous document with an empty SRS attribute in the bounding box element.
