### ISSUE TITLE
Cyclorama foto wordt niet getoond in Flamingo 4

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#690]
### Where?
Viewer 
### What happened
Klikken op een bollejte levert een grijs scherm op. De ImageID wordt niet correct opgehaald.

### What did you expect?
Een rondkijkfoto te zien.

### Reproduce
Ga naar de applicatie, zoom in, klik op een blauw bolletje 
### Version
4.7.5.

### URL
http://venray.flamingo4.nl/viewer/app/Cyclorama

**Comment by mprins** [comment]
not a Flamingo issue: the cyclo viewer shockwave applet loading (https://www.globespotter.nl/v2/api/bapi/viewer_bapi.swf) is refused by the browser because the certificate is invalid.

> Your connection is not private

> Attackers might be trying to steal your information from www.globespotter.nl (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

> This server could not prove that it is www.globespotter.nl; its security certificate is from *.azurewebsites.net. This may be caused by a misconfiguration or an attacker intercepting your connection.

the cyclo wbesite should fix their TLS certificate or the url of the applet should be changed
