### ISSUE TITLE
Minimize button overview map not visible

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#698]
### Where?
viewer

### What happened
The minimize button for the overview map is working, however, it is not visible

### What did you expect?
Button should appear

### Reproduce
Configure the overviewcomponent and open the viewer with the component. Use the mouse to search around the edges for the button (the mouse pointer should change when you find it).

### Version
4.7.4 and 4.7.5

### URL
http://flamingo4.b3p.nl/viewer/app/BAG%20(Testomgeving)/v1 -> the button is on the right side of the overview map

**Comment by mprins** [comment]
transparent image with only white pixels is not visible on the white background, either set the background-color or change the image
