### ISSUE TITLE
Flamingo does not work with Risicokaart WFS

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#704]
WMS: http://servicespub.risicokaart.nl/rk_services_pub/services/WMS-risicokaart
WFS: http://servicespub.risicokaart.nl/rk_services_pub/services/WFS-risicokaart

In the GetFeature response the schemaLocation has an extraneous space at the beginning. This causes the exception "you must have an even number of terms" in org.geotools.xml.XMLSAXHandler:342.

Solution is to trim() the schemaLocation before splitting it in GeoTools.

**Comment by matthijsln** [comment]
The GetFeature error is reproduced by using the AttributeList, the FeatureInfo produces the following error:

Exception: java.util.NoSuchElementException: Could not aquire feature:java.io.IOException: org.geotools.ows.ServiceException: Error in XML document (line: -1, character offset: 0): No attribute with name {null}units.

Perhaps the same cause.

**Comment by mtoonen** [comment]
Responsibility of geotools, no way to fix this in flamingo. Fix in https://github.com/mtoonen/geotools/tree/extraSpaceBreaksParsing
