### ISSUE TITLE
editing `date` fails

### ISSUE THREAD

**Issue by mprins** [flamingo-geocms/flamingo#711]
### Where?

viewer, editcomponent
### What happened

the edit field stays blank when the postgresql type is "date"
### What did you expect?

date should be editable
### Reproduce

How can we reproduce this? A detailed, step-by-step explanation helps us to understand what went wrong.
### Version

4.7.7?

**Comment by mprins** [comment]
https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/webapp/viewer-html/components/Edit.js#L520

**Comment by mprins** [comment]
more info was requested

**Comment by mtoonen** [comment]
Implemented
