### ISSUE TITLE
Metadata window is too small at start

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#713]
### Where?

Was it in the viewer of the viewer-admin? Which page, of which component.
In Flamingoviewer
### What happened

Something odd/unexpected/terrible happened. Tell us everything!
Metadatawindow is too small when opened. This can not be configured in the admin module
### What did you expect?

What should have happened?
I would expect the new browserwindow to open fullscreen
or possibility to adjust size in viewer-admin
### Reproduce

How can we reproduce this? A detailed, step-by-step explanation helps us to understand what went wrong.
http://gisopenbaar.overijssel.nl/viewer-geodata/app/master/v1# 
in map "stedelijk gebied" layer "bebouwde kommen in Overijssel" push "informatie over kaartlaag"
### Version

Which version of flamingo do you use (ie. http://<server>/viewer/about.jsp)
Version:    4.7.7
Build time: 04.10.2016 @ 14:34:24 CEST
### URL

Where can we find an application which has the bug?
http://gisopenbaar.overijssel.nl/viewer-geodata/app/master/v1#

**Comment by geertplaisier** [comment]
The width/height of the popup is configured inside the LayerContext component in tab Layout. Empty the width/height fields for 100% width/height.
