### ISSUE TITLE
Name (' weergavenaam' )of the service is deleted after update

### ISSUE THREAD

**Issue by NiekBouma** [flamingo-geocms/flamingo#722]
### Where?
Viewer-admin, Services and map layers

### What happened
I updated an existing service, after that the name ('weergavenaam' ) of the service is gone.

### What did you expect?
The name of the service should not be deleted when updating a service

### Reproduce
http://flamingo4.b3p.nl/viewer-admin, update a service the name will be gone in the services tree on the left side. The work around is to enter the name of the service again and save it, and not update the service again after that.

### Version
Which version of flamingo do you use (ie. http://<server>/viewer/about.jsp)
4.7.7 
### URL
http://flamingo4.b3p.nl/viewer-admin

**Comment by mtoonen** [comment]
Duplicate #249
