### ISSUE TITLE
Protect against brute force login

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#726]
### Where?
Login to viewer or admin

### What happened
It is possible to try to login with an infinite number of username/password combinations. This make it possible to do a brute force attack.

### What did you expect?
After a certain number of unsuccessful logins, the user should be excluded from login for a certain time.

### Reproduce
Login with incorrect username/password and repeat.

### Version
any version

### URL
any application

**Comment by cvanlith** [comment]
This may be solved by configuring the containerbased authentication appropriately. In Tomcat one should use LockOutRealm in stead of the currently used CombinedRealm.

**Comment by mprins** [comment]
seems a one-liner replacement; 
LockOutRealm has some options that can be set, but I think the defaults are sane (300second (5min) lockout after 5 failed attempts); failed attempts will show up in the catalina.out log

see: https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/realm/LockOutRealm.html#failureCount
