### ISSUE TITLE
Creating mash-ups, results in different startkaarten

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#747]
### Version
5.0.0-beta3
4.7.10-rc2 

### Browser info
You are using Chrome Dev 55.0.2883.87 on Windows 10

### URL
maps.vlaardingen.nl

### Where?
viewer-admin

### What happened
When creating a mash-up, not all startkaarten are loaded(or not at all..)

### Reproduce

Step 1:
As a test, I created a mash-up of a application. Here, only the OpenBasisKaart is included in the startkaarten. (So nothing from the parent application) Here I have added random number of  kaartgroepen(A, B & C). After saving, there is only OpenBasisKaart and A.

Step 2:
Then I make a mash-up of Step 2. Here are all the kaartgroepen of the parent application + 1 Random(D) extra kaartgroepen. 

A mash-up made from the mash-up of Step 2. Now are all the  kaartgroepen from parent application (from step 1) are visible, but not startkaart D(from step 2).

**Comment by mtoonen** [comment]
Is this still relevant after the 4.7.10-rc3 release?
