### ISSUE TITLE
Sorting attributen doesn't show in feature info ----> Meer

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#752]
### Version
Version:	5.0.0-beta3 (latest release: v4.7.9, dd. Thu Dec 15 2016)
Build time:	22.12.2016 @ 16:15:43 CET
Build by:	Mark Prins
Git details
Git branch:	52d3823e3065bc908580d4bf613061d8051fe237
Git remote url	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id:	52d3823
Git commit full id:	52d3823e3065bc908580d4bf613061d8051fe237
Git commit time:	22.12.2016 @ 15:56:55 CET
Runtime information

OS info:	Linux 3.2.0-4-amd64 amd64
Java version:	Oracle Corporation 1.8.0_66
Servlet container info:	Apache Tomcat/7.0.28

### Browser info
You are using Chrome Dev 55.0.2883.87 on Windows 10
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

### URL
http://flamingo4.b3p.nl/viewer-admin

### What happened
When an attribuut sorting is changed, the sorting isn't changed in feature info ----> Meer:
![image](https://cloud.githubusercontent.com/assets/25010187/22107530/ab1e55a8-de4e-11e6-9b0a-8baaec03ea4c.png)

![image](https://cloud.githubusercontent.com/assets/25010187/22107404/e4db2fb0-de4d-11e6-876a-7eaf0d51827d.png)

**Comment by mtoonen** [comment]
This is by design, the order is only used in the AttributeList. This is new functionality, for which we can make a quote.
