### ISSUE TITLE
Pass projection/srsname to wfs featureinfo request

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#761]
Currently, when a featureinfo request is done, the point doesn't have the srsname of the coordinates, even though it's a valid attribute of a gml:point.
<SERVER>&VERSION=1.0.0&MAXFEATURES=11&FILTER=<Filter+xmlns="http://www.opengis.net/ogc"+xmlns:gml="http://www.opengis.net/gml"><DWithin><PropertyName>geom</PropertyName><gml:Point><gml:coordinates+decimal="."+cs=","+ts="+">173280.0,557853.44</gml:coordinates></gml:Point><Distance>0.0</Distance></DWithin></Filter>&TYPENAME=test:gem_2014_new

**Comment by mprins** [comment]
Should this be fixed in GeoTools? Or are we constructing this filter and URL ourselves?

**Comment by mtoonen** [comment]
No, we are constructing this filter. Probably just need to set the srs to the geometry.
