### ISSUE TITLE
Filtering of dropdown box (in search component) can not be undone

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#769]
### Version
5.0 beta, 4.7?

### Where?
search component

### What happened
more than one search optiona are present, type one letter to select a search option, get autosuggest list with applicable search options, this is not what you want, remove character and hope to see full list again, this does not happen, even clicking on the triangle shows only the filtered options.
Only F5 resolves this

### What did you expect?
after removing character the full list should be available again.

**Comment by geertplaisier** [comment]
This is only an issue in v4.x and resolved in v5.x
