### ISSUE TITLE
Feature info isn't loading in map layer Voorzieningen(Mapservert test).

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#771]
### Version

Version:	4.8.0-rc2 (latest release: v4.7.9, dd. Thu Dec 15 2016)
Build time:	10.02.2017 @ 10:44:02 CET
Build by:	Meine Toonen
Git details
Git branch:	7efe1430cc447887e34129b804e3e456ecbe8447
Git remote url	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id:	7efe143
Git commit full id:	7efe1430cc447887e34129b804e3e456ecbe8447
Git commit time:	10.02.2017 @ 10:26:31 CET
Runtime information

OS info:	Linux 3.2.0-4-amd64 amd64
Java version:	Oracle Corporation 1.8.0_66
Servlet container info:	Apache Tomcat/8.0.14 (Debian)

### Browser info
You are using Chrome Dev 56.0.2924.87 on Windows 10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### URL
http://test.flamingo4.nl/viewer/app/Test_omgeving

### Where?
Viewer

### What happened
Feature info isn't loading in map layer Voorzieningen(Mapservert test).

**Comment by mtoonen** [comment]
Erroneous mapserver. Not present on local mapserver. Invalid
