### ISSUE TITLE
Different components - Can't find a response parser factory for GET_FEATURE

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#773]
Version

Version:	4.8.0-rc2 (latest release: v4.7.9, dd. Thu Dec 15 2016)
Build time:	10.02.2017 @ 10:44:02 CET
Build by:	Meine Toonen
Git details
Git branch:	7efe143
Git remote url	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id:	7efe143
Git commit full id:	7efe143
Git commit time:	10.02.2017 @ 10:26:31 CET
Runtime information

OS info:	Linux 3.2.0-4-amd64 amd64
Java version:	Oracle Corporation 1.8.0_66
Servlet container info:	Apache Tomcat/8.0.14 (Debian)

Browser info

You are using Chrome Dev 56.0.2924.87 on Windows 10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

URL

http://test.flamingo4.nl/viewer/app/Test_omgeving

Where?

Viewer

### What happened
Ussing mapping layer Bestemmingsplangebied(Deegree test) and the components: Attribuutinformatie, Spatial Filter, Snapping, Invloedsgebieds plaatje & Dataselectie give you the following error:

Fout bij ophalen features: org.geotools.factory.FactoryNotFoundException: Can't find a response parser factory for GET_FEATURE/'application/vnd.ogc.se_xml;charset=UTF-8'

These map layers are based on WFS's that where loaded before the upgrade to the newest version of Flamingo. 

The issue from above, is probably the same as  issue #770.

**Comment by Tom-Kooy** [comment]
All the components are still getting the same error, except Attribuutinformatie.

**Comment by mtoonen** [comment]
Cannot reproduce
