### ISSUE TITLE
Not able to request data joined/related WFS featuretypes in attributenlijst

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#777]
### Version
viewer-admin 4.8.0-rc3 

### Browser info
firefox 51

### URL
http://test.flamingo4.nl/viewer/app/Test_omgeving

### Where?
viewer

### What happened
Was using a geoserver WFS (name: Test_omgeving_geoserver2) when the following problem ensued:
Made a relate buurt-gemeente on attribute 'GM_CODE' in viewer-admin and trying to open the relate in the attributenlijst in the viewer generated this error: 

Fout bij ophalen features: java.lang.RuntimeException: org.geotools.data.wfs.internal.WFSException: Exception parsing server exception report; org.geotools.data.wfs.internal.WFSException: Exception parsing server exception report; java.io.IOException: Unrecognized server error

Same happened when i joined the featuretypes.

Made a relate gemeente-buurt on 'GM_CODE' in viewer-admin and did not get an error, but didn't get any data either. I did see the names of the attributes i wanted to see. Same happened when i joined the featuretypes.

### What did you expect?
Not to get the error and to get to see the data

### Reproduce

  1. See above and/or activate layer 'Relate test' in application 'Test_omgeving'
  2. 
  

### Server log
No relevant server log

**Comment by mtoonen** [comment]
Not able to reproduce. Was probably misconfigured and the data was different than expected.
