### ISSUE TITLE
Not able to create graph of Geoserver WFS data

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#778]
### Version
4.8.0-rc3

### Browser info
FF 51

### URL
http://test.flamingo4.nl/viewer/app/Test_omgeving

### Where?
Viewer

### What happened
Configured the graph component in viewer-admin to generate a graph of the number of residents (AANT_INW) in a municipality (GM_NAAM). 

Graph component in viewer doesn't generate a graph

### What did you expect?
To see a single bar in a graph which would represent the number of residents in a municipality. I would expect to at least see a graph. But after klicking activating the layer in viewer, activating the component, activating the layer in the component and then clicking in the map, i don't even get a pop-up with an empty graph

### Reproduce
see 'what happened' or activate the Graph component on http://test.flamingo4.nl/viewer/app/Test_omgeving
  

### Server log
No server log

**Comment by mtoonen** [comment]
fixed with: https://github.com/geotools/geotools/pull/1478
