### ISSUE TITLE
no default value for dataselectie component in Deegree and Geoserver

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#780]
### Version
4.8.0-rc3

### Browser info
FF 51

### URL
http://test.flamingo4.nl/viewer/app/Test_omgeving
And
http://test.flamingo4.nl/viewer-admin

### Where?
Boomstructuur met kaartlagen in viewer-admin. 

### What happened
Configured layer cbs_gemeentes_2014 (with WFS attribuutbron). I wanted to use attribute 'GM_CODE' in the Dataselectie component. However, klicking the DB button to generate a list of potential values won't work.

![db button does not work](https://cloud.githubusercontent.com/assets/13237783/22977888/ca0d217c-f390-11e6-8047-8968d110bcc7.png)

### What did you expect?
I expected to get a list of potential values of this attribute.

### Reproduce
see above.

Worth noting: filling out a usable value in the default waarde field does work in the dataselectie component in the viewer itself.

otherwise you get the following value in the dataselectie component in the viewer itself: 'extModel394-1' -> you cannot change this in that case

### Server log
No server log

**Comment by mtoonen** [comment]
Probably fixed with: https://github.com/geotools/geotools/pull/1478
Not sure though
