### ISSUE TITLE
Layer isn't displayed on the pdf print

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#787]
### Version
Tested it in 2 versions:

**http://flamingo4.b3p.nl :**
Flamingo viewer

Version:	5.0.0-beta3
Build time:	22.12.2016 @ 16:15:43 CET
Build by:	Mark Prins
Git details
Git branch:	52d3823e3065bc908580d4bf613061d8051fe237
Git remote url	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id:	52d3823
Git commit full id:	52d3823e3065bc908580d4bf613061d8051fe237
Git commit time:	22.12.2016 @ 15:56:55 CET

**http://kaarten.gelderland.nl/ :**
Flamingo viewer

Version:	4.6.1
Build time:	
Build by:	
Git details
Git branch:	
Git remote url	
Git commit abbrev id:	
Git commit full id:	
Git commit time:	
### Browser info

You are using Chrome Dev 56.0.2924.87 on Windows 10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### URL
http://kaarten.gelderland.nl/viewer/app/thema_bodemverontreinigingen

http://flamingo4.b3p.nl/viewer/app/Tom%20Test

### Where?
In the viewer, when selected a layer from the wms https://gis-squitibis.roxit.nl/Gelderland/wms?SERVICE=WMS& , the layer is displayed as it should. But when we use the printing component to print to PDF, the layer isn't displayed.

In example below, we us layer locaties:

Viewer:
![viewer](https://cloud.githubusercontent.com/assets/25010187/23464248/b7046a86-fe94-11e6-9b37-cfd522fecd81.jpg)

PDF:
![pdf](https://cloud.githubusercontent.com/assets/25010187/23464259/bd827f7e-fe94-11e6-815b-441e89256b14.jpg)

### What did you expect?
The selected layer, should also displayed on the pdf print.

**Comment by mprins** [comment]
log file?

**Comment by mtoonen** [comment]
Works for me. Did you try to zoom in more? It's a layer with a
minscale/maxscale. Maybe it was out of reach?

**Comment by mtoonen** [comment]
Was fixed in 4.7.4 (probably)
