### ISSUE TITLE
Returning from redlining component does not reinstate google navigation tool

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#805]
### Version
4.8.0

### Browser info
chrome

### URL
http://middendelfland.flamingo4.nl/viewer/app/Midden-Delfland/v1

### Where?
Returning from redlining component to normal operation (probably other components have same issue)

### What happened
Returning from redlining component does not reinstate google navigation tool. Before starting redlining tool the google naviagation tool was active. After closing the redlining component not anymore. Manual click on google navigation tool is required.

### What did you expect?
automatic reinstate of previously active tool after closing component.

### Reproduce
click, zoom using google naviagation tool
use redlining tool by drawing someting
close redlining tool
try clicking and zooming, not possible because tool is not active.

**Comment by geertplaisier** [comment]
This is configurable in "Tekenen" component. Tick the box behind "Heractiveer de vorige tools".
