### ISSUE TITLE
Dragging a component in a region, should not should not show icons

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#809]
this happens in ext 6.x / 5.0.0-branch

![image](https://cloud.githubusercontent.com/assets/1853172/24851202/215e33aa-1dd3-11e7-8cef-77cf724e9dba.png)

**Comment by geertplaisier** [comment]
Fixed by bca9cd8f6dcdb2b2cf329360a20b2998e60df294
