### ISSUE TITLE
WMS  service isn't showing in menu, the first time

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#828]
### Version
Flamingo viewer-admin
Version: 	5.0.0-beta5 (latest release: v4.8.0, dd. Tue Feb 28 2017)
Build time: 	19.04.2017 @ 13:41:33 CEST
Build by: 	Meine Toonen
Git details
Git branch: 	df7621284e320fb9f81fa83ae6350f8fd9eac60c
Git remote url 	git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id: 	df76212
Git commit full id: 	df7621284e320fb9f81fa83ae6350f8fd9eac60c
Git commit time: 	19.04.2017 @ 13:38:04 CEST
Runtime information
OS info: 	Linux 3.2.0-4-amd64 amd64
Java version: 	Oracle Corporation 1.8.0_66
Servlet container info: 	Apache Tomcat/8.0.14 (Debian)

### Browser info
You are using Firefox 52.0 on Windows 10
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

### URL
http://test.flamingo4.nl/viewer-admin/

### Where?
viewer-admin - Services en kaartlagen

### What happened
If there is no attribuutbron in flamingo, the wms service isn't visible in the left menu:
![image](https://cloud.githubusercontent.com/assets/25010187/25231127/e8c8e6dc-25d6-11e7-8384-5085343062cc.png)

![image](https://cloud.githubusercontent.com/assets/25010187/25231121/e3c55472-25d6-11e7-8beb-036e92f8eca1.png)

If the page is refreshed, the WMS service is showed in the left menu.

If there is a attribuutbron available in flamingo, the WMS service is showed when it is loaded/saved:

![image](https://cloud.githubusercontent.com/assets/25010187/25231115/dda39a68-25d6-11e7-842b-eb26682a2634.png)

### What did you expect?
It should be, that the WMS service always is visible. Even if, it is a brand new environment.

**Comment by mtoonen** [comment]
Cannot reproduce in a clean install. Neither in firefox and in chrome.

**Comment by mtoonen** [comment]
Happens when adding it to an empty category: probably the category isn't expanded.
