### ISSUE TITLE
No warning when using wrong schema in DB attribuutbron

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#831]
### Version
Flamingo viewer-admin
Version: 5.0.0-beta5 (latest release: v4.8.1, dd. Thu Apr 20 2017)
Build time: 19.04.2017 @ 13:41:33 CEST
Build by: Meine Toonen
Git details
Git branch: df76212
Git remote url git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id: df76212
Git commit full id: df76212
Git commit time: 19.04.2017 @ 13:38:04 CEST
Runtime information
OS info: Linux 3.2.0-4-amd64 amd64
Java version: Oracle Corporation 1.8.0_66
Servlet container info: Apache Tomcat/8.0.14 (Debian)

### Browser info
You are using Firefox 52.0 on Windows 10
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0>

### URL
http://test.flamingo4.nl/viewer-admin/

### Where?
viewer-admin - Bronnen - Attribuutbronnen - Nieuwe attribuutbron

### What happened
When adding a new database attribuutbron, the attribuutbron saves when there is wrong used schema:
![image](https://cloud.githubusercontent.com/assets/25010187/25266774/b363b57a-2672-11e7-9092-7a10edb62f00.png)
pu**p**lic should be pu**b**lic

### What did you expect?
I should get a warning like:
The attribuutbron couldn't save, because the shema doesn't exist.

**Comment by mtoonen** [comment]
By design.
