### ISSUE TITLE
PDOK Adreszoeker doesn't return search results that partially match

### ISSUE THREAD

**Issue by FrieseWoudloper** [flamingo-geocms/flamingo#866]
### Version
4.8.0

### Browser info
Internet Explorer 11

### URL
n.a.

### Where?
viewer

### What happened
I configured a viewer that uses PDOK Adreszoeker. You only get search results in the dropdown list when the search term is perfectly matched (as a whole). For example: 'Schoolstr' doesn't yield any results, but 'Schoolstraat' does. Would it be possible to add an option to use wildcards?

### What did you expect?
I expected the viewer to already give me some search suggestions when I entered part of a search term.

### Reproduce
n.a.

**Comment by mprins** [comment]
Flamingo uses the results as provided by the "Locatieserver free endpoint (vrije geocodeerservice)" 
https://github.com/PDOK/locatieserver/wiki/Zoekvoorbeelden-Locatieserver#vrije-geocodeerservice and https://github.com/PDOK/locatieserver/wiki/API-Locatieserver#5vrije-geocoder-service

it seems to be a limitation of the service.
