### ISSUE TITLE
Bookmark can't be added to bookmarks in browser

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#868]
### Version
4.8.1 and 5.0.0 beta 8

### Browser info
IE and FF 53 and chrome

### URL
http://flamingo4.b3p.nl/viewer/app/Gemeente_Goeree_Overflakkee_case_1/v1

### Where?
viewer - bookmark component

### What happened
the button to ad a bookmark to favorites/bookmarks in your browser is not visible in FF and Chrome and not working in IE

### What did you expect?
clicking 'toevoegen aan favorieten' should add the url as a bookmark. 
A bookmark is added in Flamingo4 however (viewer-admin - gegevensregister - bookmarks)

**Comment by mtoonen** [comment]
fixed in newer versions.
