### ISSUE TITLE
WMS proxy does not work

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#876]
### Version
Version:	5.0.0-beta8
Build time:	02.06.2017 @ 10:23:17 CEST

### URL
https://utrecht.flamingo4.nl/viewer/app?unknown=true

### Where?
Viewer, add plannenbank_commentaar layer

### What happened
Browser requests url to /viewer/action/proxy/wms:

https://utrecht.flamingo4.nl/viewer/action/proxy/wms?url=http%3A%2F%2Fplannenbank2.provincie-utrecht.nl%2Fdeegree-plannenbank-oracle%2Fservices%3F&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&SRS=EPSG%3A28992&VERSION=1.1.1&LAYERS=plannenbank_commentaar&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=TRUE&NOCACHE=true&MINRESULUTION=0.001&MAXRESOLUTION=1000000&QUERY_LAYERS=plannenbank_commentaar&SERVICE=WMS&REQUEST=GetMap&BBOX=123425.34,444818.76,149821.5,467182.92&WIDTH=982&HEIGHT=832

It appears the &'s should be fully urlencoded and the application id parameter is missing.

The viewer returns the error 
```
java.lang.IllegalArgumentException: id to load is required for loading
	org.hibernate.event.LoadEvent.&lt;init&gt;(LoadEvent.java:89)
	org.hibernate.event.LoadEvent.&lt;init&gt;(LoadEvent.java:61)
	org.hibernate.impl.SessionImpl.get(SessionImpl.java:1002)
	org.hibernate.impl.SessionImpl.get(SessionImpl.java:998)
	org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:779)
	org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:754)
	nl.b3p.viewer.stripes.ProxyActionBean.getRequestRL(ProxyActionBean.java:232)
	nl.b3p.viewer.stripes.ProxyActionBean.proxyWMS(ProxyActionBean.java:146)
	nl.b3p.viewer.stripes.ProxyActionBean.proxy(ProxyActionBean.java:130)
```

### What did you expect?
https://webkaart.provincie-utrecht.nl/viewer/action/proxy/wms?url=http%3A%2F%2Fplannenbank2.provincie-utrecht.nl%2Fdeegree-plannenbank-oracle%2Fservices%3F&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&SRS=EPSG%3A28992&VERSION=1.1.1&LAYERS=plannenbank_commentaar&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=TRUE&NOCACHE=true&QUERY_LAYERS=plannenbank_commentaar&SERVICE=WMS&REQUEST=GetMap&BBOX=127436.86,440788.04,152515.9,463152.2&WIDTH=933&HEIGHT=832

Version:	4.5.5-SNAPSHOT-d92a5a7
Build time:	12.08.2015 @ 09:04:03 CEST

**Comment by mprins** [comment]
I think this has been fixed now
