### ISSUE TITLE
Component Bookmark doesn't show

### ISSUE THREAD

**Issue by Tom-Kooy** [flamingo-geocms/flamingo#881]
### Version
1 | 2
-- | --
Version: | 5.0.0-beta10 (latest release: , dd. Tue May 09 2017)
Build time: | 23.06.2017 @ 16:30:39 CEST
Build by: | Meine Toonen
Git details
Git branch: | 198ae89309bf87ea3467f38870cfbd551bf304fe
Git remote url | git@github.com:flamingo-mc/flamingo.git
Git commit abbrev id: | 198ae89
Git commit full id: | 198ae89309bf87ea3467f38870cfbd551bf304fe
Git commit time: | 23.06.2017 @ 16:29:16 CEST

### Browser info
You are using Chrome Dev 59.0.3071.115 on Windows 10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

### URL
https://utrecht.flamingo4.nl/viewer/app/Webkaart

### Where?
Viewer- Component Bookmark

### What happened
You can click the button bookmark in the application, nut nothing happends.. 

### What did you expect?
The component bookmark, should show. 

### Reproduce

  1. Add component bookmark  to application
  2. Open the application
  3. Click on the bookmark button. 
  

### Server log
relevant section of the server log:
[geo-viewer-utrecht.txt](https://github.com/flamingo-geocms/flamingo/files/1127741/geo-viewer-utrecht.txt)

**Comment by mtoonen** [comment]
Fixed.
