### ISSUE TITLE
no feature info on filtered objects

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#927]
### Version
5.0.0-SNAPSHOT-c9dc2ea

### Browser info
Google Chrome is up-to-date
Versie 62.0.3202.62 (Officiële build) (64-bits)

### URL
https://flamingo4.b3p.nl/viewer-admin

### Where and/or What
it not possible to get feature info from objects that are filtered by spatial filter

### What happened
no feature info balloon on filtered objects

### What did you expect?
show balloon

### Reproduce
filter objects
click to get feature info

**Comment by cvanlith** [comment]
cirkel is square is spatial filter

**Comment by geertplaisier** [comment]
Fixed with #940
