### ISSUE TITLE
simple filter checkbox default irregular behavior

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#933]
### Version
5.0.0-SNAPSHOT-c9dc2ea

### Browser info
Google Chrome is up-to-date
Versie 62.0.3202.62 (Officiële build) (64-bits)

### URL
https://flamingo4.b3p.nl/viewer-admin

### Where and/or What
simple filter checkbox default irregular behavior

### What happened
checkbox default checked but this was not manually set
when resetting filter in viewer, checkbox reappears but filter was completely removed

### What did you expect?
checkbox not set,
and if set, reset should set the default and the filter should respect that

### Reproduce
see above

**Comment by geertplaisier** [comment]
Fixed by #939
