### ISSUE TITLE
Configurtie verdwijnt 

### ISSUE THREAD

**Issue by Nieuwland** [flamingo-geocms/flamingo#941]
### Version
Which version of flamingo do you use: 
4.7.7
### Browser info

Firefox 54 on Windows 10
### URL

https://anlbviewer-acc.portaalnatuurenlandschap.nl/anlb-flamingo-admin/action/chooseapplication/view

### Where and/or What

Viewer-admin. Bij toevoegen of beheren van de services in het gegevensregister

### What happened

O.a. de naam van de service verdwijnt maar ook de applicaties waarin de service waarin deze gebruikt worden verdwijnen

### Screenshots

Configuratie blijft zoals die is ingevoerd
### Reproduce
How can we reproduce this? 

  1. Nieuwe categeorie aanmaken
  2. Nieuwe service aanmaken
  3. Scherm verversen.

Het probleem treed niet consequent op maar komt wel regelmatig voor.

**Comment by Nieuwland** [comment]
Bij deze de log. 
Tijdens deze sessie is o.a. de lijst met gebruikte applicaties leeg geraakt
[geo-viewer-admin.log](https://github.com/flamingo-geocms/flamingo/files/1456775/geo-viewer-admin.log)

**Comment by mprins** [comment]
4.7.7 is no longer a supported version, please open a new ticket following the issue template if you can reproduce this in the latest release (either 4.8.1.7 or v5.0.0-beta12)
