### ISSUE TITLE
Opgeslagen wachtwoord van services blijft niet opgeslagen

### ISSUE THREAD

**Issue by Nieuwland** [flamingo-geocms/flamingo#942]
### Version
Which version of flamingo do you use: 
4.7.7
### Browser info

Firefox 54 on Windows 10
### URL

https://anlbviewer-acc.portaalnatuurenlandschap.nl/anlb-flamingo-admin/action/chooseapplication/view

### Where and/or What

Viewer-admin. Bij het ophalen van de services uit een beveiligde GeoServer workspace geven we het wachtwoord mee.

### What happened

Bij het opvragen van de Flamingo applicaties waarin de beveiligde services worden gebruikt vraagt Flamingo wederom om de inlog gegevens van de services

### Screenshots

Dat de kaartlagen getoond worden zonder dat er om inlog gegevens gevraagd wordt
### Reproduce
How can we reproduce this? 

  1. Nieuwe service aanmaken
  2. Inlog gegevens invullen
  3. Applicatie waarin de service gebruikt wordt activeren en openen

**Comment by mprins** [comment]
Om de credentials van een geconfigureerde service te gebruiken moeten alle requests via de flamingo proxy lopen door het betreffende vinkje " Gebruik proxy om kaarten op te halen." aan te zetten, als dat niet aan staat zal de client zelf om authenticatie gevraagd worden; de credentials worden nooit naar de client gestuurd.

NB. De proxy is sinds 4.7.7 volledig herschreven vanwege een security issue

**Comment by mprins** [comment]
Your report is missing key information for debugging and or analysis. Please use the issue template provided.
