### ISSUE TITLE
Flamingo crasht bij het updaten van een service

### ISSUE THREAD

**Issue by Nieuwland** [flamingo-geocms/flamingo#943]
### Version
Which version of flamingo do you use: 
4.7.7
### Browser info

Firefox 54 on Windows 10
### URL

https://anlbviewer-acc.portaalnatuurenlandschap.nl/anlb-flamingo-admin/action/chooseapplication/view

### Where and/or What

Viewer-admin. Bij updaten van de de ANLB service

### What happened

Krijg een fout melding bij het updaten van bovengenoemde service

### Screenshots

Update van de service
### Reproduce
How can we reproduce this? 

  1. Klik op update van o.a. de ANLB service (zonder naam)

**Comment by Nieuwland** [comment]
Bij deze de log file van het moment van updaten van de service
[geo-viewer-admin.log](https://github.com/flamingo-geocms/flamingo/files/1456765/geo-viewer-admin.log)

**Comment by mprins** [comment]
Your report is missing key information for debugging and or analysis. Please use the issue template provided.
the log file does not show the crash / is incomplete

**Comment by Nieuwland** [comment]
Beste Marco,

Bij de de log van de nieuwe crash. 
Het vreemde (gister) ook al is dat de crash in de logfile niet terug is te vinden.
[geo-viewer-admin.log-1.txt](https://github.com/flamingo-geocms/flamingo/files/1457556/geo-viewer-admin.log-1.txt)

**Comment by mprins** [comment]
4.7.7 is no longer a supported version, please open a new ticket following the issue template if you can reproduce this in the latest release (either 4.8.1.7 or v5.0.0-beta12)
