### ISSUE TITLE
Mashup applicatie neemt onbedoelde Niveau's met kaartlagen mee.

### ISSUE THREAD

**Issue by Nieuwland** [flamingo-geocms/flamingo#944]
### Version
Which version of flamingo do you use: 

4.7.7

### Browser info
Firefox 54 on Windows 10

### URL
https://anlbviewer-acc.portaalnatuurenlandschap.nl/anlb-flamingo-admin/action/applicationsettings/?view=&application=2

### Where and/or What
Viewer-admin. Het aanmaken van een nieuwe Mashup Applicatie gaat niet als verwacht. 

### What happened
Ook andere Niveau's met kaartlagen uit de Boomstructuur met Kaartlagen van de Hoofdapplicatie worden aan de Mashup applicatie toegevoegd. Dit gebeurt willekeurig.

### What did you expect?
Startkaartbeeld Mashup is identiek aan Startkaartbeeld Hoofdapplicatie

### Reproduce
How can we reproduce this? 

  1. Selecteren Hoofdapplicatie <Natuurbeheerplan>
  2. Kies Maak mashup
  3. Vergelijk Startkaartbeeld Mashup met Startkaarbeeld Hoofdapplicatie.

**Comment by mprins** [comment]
Both mashups and startkaartbeeld have seen many changes and improvements since 4.7.7. 
You can open a new ticket providing the requested information if your problem persists with the current release (4.8.1.7) or the upcoming 5.0.x release currently in beta.
