### ISSUE TITLE
Ignition component improvements

### ISSUE THREAD

**Issue by mtoonen** [flamingo-geocms/flamingo#954]
## Testresultaten aanpassing Atlas van Overijssel

- [x] Titel aanpassen van Ontbrandingsaanvraag naar Vuurwerkevenementen

- [x] Onderstaand aanpassen: het betreft geen aanvraag maar een situatietekening, dus het woord aanvraag wijzigen in situatietekening
![image](https://user-images.githubusercontent.com/1853172/33434690-4fac28e6-d5e0-11e7-96b4-87db0fd8be8a.png)

- [x] ‘Nieuwe aanvraag indienen’ moet gewijzigd worden in ‘nieuwe situatietekening maken’.
‘eerdere aanvraag inladen’ moet gewijzigd worden in ‘eerdere situatietekening inladen’.

- [x] Bij alle koppen zoals ‘Afsteeklocatie toevoegen’   een + toevoegen zodat de gebruiker weet dat je met die knop iets kunt toevoegen.
![image](https://user-images.githubusercontent.com/1853172/33434701-55253d4e-d5e0-11e7-90e8-111f2d45f6b7.png)

- [x] De kop ‘Afstandslijn’ is niet nodig, het programma moet de afstand van rand afsteeklocatie tot rand veiligheidszone zelf weergeven op de uiteindelijke situatietekening op basis de gekozen vuurwerkcategorie.

- [x] Bij fan uitworp moet handmatig een zoneafstand worden ingevuld. Dit moet het programma zelf berekenen want fanshape is alleen van toepassing bij 2 categorieën vuurwerk en is altijd de veiligheidsafstand + 50%. Het betreft de categorieën
Consumentenluchtvuurwerk met een kaliber tot en met 1 inch
Consumentenluchtvuurwerk met een kaliber vanaf 1 tot 2 inch

- [x] Na ‘Berekenen veiligheidszone’ komt de veiligheidszone in beeld:
De teksten mbt loodlijnen komen in de tekening. Deze moeten niet zichtbaar zijn.

- [x] Bij het inkleuren van de veiligheidszone is de ondergrond niet meer zichtbaar. Het inkleuren is niet nodig, de randen moeten wel duidelijk zijn, waarbij per afsteeklocatie een andere kleur wordt gebruikt. 
- [x] Bij het tekenen van hulp- en afstandslijnen deze in de vorm van een lijn aanbieden. Bij intekenen kan deze dan langer of korter worden gemaakt.

- [x] Geert: Bij de zoneafstand moet worden aangegeven dat de vuurwerkcategorie met de grootste veiligheidsafstand moet worden geselecteerd. Die bepaalt namelijk de te hanteren veiligheidszone. Op 1 afsteeklocatie kunnen namelijk meerdere categorieën vuurwerk worden opgesteld.

- [x] Geert: Bij het bepalen van de zoneafstand is het mogelijk om ‘Anders, namelijk…’ te selecteren. Hier moet dan nog wel worden aangeven welk vuurwerkcategorie het betreft. Dit is nu niet duidelijk. Nu kan alleen een zoneafstand aangegeven worden.

- [ ] Fan uitworp (elipsevormig gebied) aanpassen in Fanshape (schuine stand).
- [ ] Bij de kop ‘Opslaan en printen’ moet onderscheid worden gemaakt in:
Situatietekening opslaan .JSON
Situatietekening opslaan .PDF
Situatietekening printen (afdruk van .PDF)

- [ ] In het uiteindelijke resultaat worden verkeerde teksten zichtbaar waaronder informatie over de loodlijnen. De afmeting van de afsteeklocatie en veiligheidsafstanden in meters ontbreken. Juist deze informatie is belangrijk! Het kan dat door verschillende afsteeklocaties er te veel informatie op de tekening komt. Wellicht is het daarom overzichtelijker wanneer een legenda gebruikt wordt waarin per afsteeklocatie aangegeven is de categorie vuurwerk en de bijbehorende veiligheidsafstand.
Dus: Afsteeklocatie 1: romeinse kaarsen t/m 2 inch - 75 meter

- [x] Geert: Het is handig om te zien waar je bent bij het maken van de situatietekening. Daarom een balk invoegen waarin oplicht in welk veld je bezig bent (voortgang). Hiermee kun je ook snel naar het tabblad navigeren om het een en ander aan te passen: 
Aanvraag – afsteeklocaties – publiekslocatie – berekening – hulplijnen – opslaan en printen

- [x] Geert: stylen van safetyDistance lijnen

- [x] Geert: opacity in featuretypestyle

- [ ] Punten/pijlen op print correcte plek

# Configuratie werkzaamheden:

- [ ] Het component moet starten met de meest actuele luchtfoto ipv oms

- [ ] Het moet mogelijk zijn om een adres te zoeken. Omdat het een los component wordt zijn de functies die de Atlas biedt niet beschikbaar (?)

- [ ] In de Atlas van Overijssel kunnen meerdere kaarten opgehaald worden waarop vervolgens getekend kan worden. Dit moet bij het maken van de situatietekening niet mogelijk zijn; de situatietekening moet altijd gemaakt worden op de meest actuele luchtfoto!

**Comment by mprins** [comment]
@mtoonen can this be moved to the proper milestone and closed?
