### ISSUE TITLE
attributes converted to xml-elements for use in report should maintain order

### ISSUE THREAD

**Issue by cvanlith** [flamingo-geocms/flamingo#968]
When a report is created attributes are first converted to json and later to xml. In de first step (converting to json) attributes are collected in a hashmap (JSONObject) without an order. All subsequent steps can not use the order of the attributes.
In the class FeatureToJson the method JSONObject toJSONFeature(JSONObject j,....) should be refactored to JSONArray toJSONFeature(JSONArray j,...).
Order is then maintaned and can be used in reports, featureinfo-more and do on.

**Comment by mprins** [comment]
high impact change

**Comment by geertplaisier** [comment]
See branch impr/maintain-attribute-order (43d736c) for first attempt at using JSONArray instead of JSONObject

**Comment by mprins** [comment]
fixed with #970
